### ISSUE TITLE
[MU4 Issue] Reset palette causes a crash

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#10163]
https://user-images.githubusercontent.com/90187801/147260956-65a18b93-833a-4421-a696-c926632f3da8.mp4

**Desktop:**
 - OS: Win10

**Comment by igorkorsukov** [comment]
@DmitryArefiev Please check, PR https://github.com/musescore/MuseScore/pull/10179
I fixed a bug that was causing the crash.
But it seems that the function of pallets reset itself works very strangely, if there are errors, I propose to log them separately, with the corresponding priorities.

**Comment by DmitryArefiev** [comment]
@igorkorsukov I've tested on Win/Mac and found some strange behavior now:

1. Reset Palette action **hides palette** instead of resetting it
2. If some elements are deleted, Reset Palette action **still crashes MU**

Please see video

https://user-images.githubusercontent.com/90187801/147489142-f07fc924-18e2-45ec-b3da-9b8433851fca.mp4

**Comment by igorkorsukov** [comment]
@DmitryArefiev Now it should be fixed! Please, check.

**Comment by DmitryArefiev** [comment]
@igorkorsukov I've checked on Win/Mac but still **can reproduce the crash**

https://user-images.githubusercontent.com/90187801/147605989-888b152c-73a4-4970-97f3-77f9e0b28a68.mp4

**Comment by VanSHOE** [comment]
Does the PR solve the issue now?

**Comment by igorkorsukov** [comment]
> Does the PR solve the issue now?

Not yet, 2 out of 3 problems solved, I'm figuring out what else is wrong

**Comment by igorkorsukov** [comment]
@DmitryArefiev I found trouble and fixed it, please check

**Comment by DmitryArefiev** [comment]
@igorkorsukov Now Reset palette doesn't cause a crash, but **dragging element within palette does it**

https://user-images.githubusercontent.com/90187801/148785187-4367721a-073b-4940-9c5b-7edeae09b4de.mp4

(this crash doesn't occur in master)

**Comment by igorkorsukov** [comment]
@DmitryArefiev Fixed it :(, Please check

**Comment by DmitryArefiev** [comment]
@igorkorsukov Now all good! Thanks!

Tested on Win10, Mac12, LinuxMint 20.2 - FIXED
