### ISSUE TITLE
[MU4 Issue] Fails to open when running native wayland

### ISSUE THREAD

**Issue by crispyricepc** [musescore/MuseScore#11244]
**Describe the bug**
When running on a wayland compositor using `-platform wayland`, the program exits with code 134

**To Reproduce**
1. Execute the appimage from the command line with the argument `-platform wayland`

**Expected behavior**
Musescore should open using a wayland windowing system

**Command line output**
```
/usr/lib64/pipewire-0.3/jack/libjack.so.0
/lib64/libnss3.so
QEventLoop: Cannot be used without QApplication
QEventLoop: Cannot be used without QApplication
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: xcb.

/tmp/.mount_MuseScpdjKJ6/AppRun: line 26: 23352 Aborted                 (core dumped) "${APPDIR}/bin/mscore-portable" "$@"
```

**Platform information**
 - OS: Linux
 - Window Manager: GNOME 41 Wayland

**Comment by crispyricepc** [comment]
> I think because only the library libqxcb.so is included at installation time in the AppImage distribution.

Should this be included in the AppImage for Linux then? AFAIK there's no downside to including this library since it just allows wayland users to not have to rely on xwayland.

> Edit: I tried what I suggested, but MuseScore 4 alpha does not seem to be forwarding Qt option `-platform` to its Qt infrastucture, so even `-platform=xcb` does not work for me

Huh, using `-platform=xcb` seems to give a response for me, and [the relevant commits on the MU4 branch](https://github.com/musescore/MuseScore/blob/cafefd76897319dd197a4263906e645274bcf95c/src/main/main.cpp#L319) suggests that the arguments are being passed to Qt.

**Comment by AntonioBL** [comment]
By setting env variable `QT_QPA_PLATFORM=<name of the plugin>` before launching the AppImage seems to work for me (but then it cannot run wayland since I am using X11).
You can thus try this:
- extract the (MuseScore 4.0 Alpha) AppImage content by running it with option `--appimage-extract`; a folder called `squashfs-root` is created
- download https://s3.amazonaws.com/utils.musescore.org/Qt5152_gcc64.7z
- copy the "wayland" plugins from folder `plugins/platforms` inside the 7z archive to `squashfs-root/plugins/platforms`
- `cd squashfs-root`
- run `QT_QPA_PLATFORM=wayland ./AppRun`

Ciao,
ABL

**Comment by AntonioBL** [comment]
I finally managed to run a virtual machine with Debian wayland, so I could test it myself.
Here you can find an AppImage of MuseScore 4.0 first alpha repacked with those platform plugins as well as the Qt-plugin folders `wayland-decoration-client`, `wayland-graphics-integration-client` and `wayland-shell-integration`:
https://drive.google.com/file/d/1naata5hkyLyZqYqlBs-bGCJbvzFrWlT9/view?usp=sharing
(I extracted the AppImage with `--appimage-extract`, copied the files and then repacked with appimagetool, https://appimage.github.io/appimagetool/ )
If you launch it with env variable `QT_QPA_PLATFORM=wayland` or `QT_QPA_PLATFORM=wayland-egl` it should use native wayland.

Ciao

**Comment by Microwave-WYB** [comment]
> I finally managed to run a virtual machine with Debian wayland, so I could test it myself. Here you can find an AppImage of MuseScore 4.0 first alpha repacked with those platform plugins as well as the Qt-plugin folders `wayland-decoration-client`, `wayland-graphics-integration-client` and `wayland-shell-integration`: https://drive.google.com/file/d/1naata5hkyLyZqYqlBs-bGCJbvzFrWlT9/view?usp=sharing (I extracted the AppImage with `--appimage-extract`, copied the files and then repacked with appimagetool, https://appimage.github.io/appimagetool/ ) If you launch it with env variable `QT_QPA_PLATFORM=wayland` or `QT_QPA_PLATFORM=wayland-egl` it should use native wayland.
> 
> Ciao

Tested on Fedora 36 but got
```
> QT_QPA_PLATFORM=wayland ./MuseScore-4.0.0.2059995262-x86_64_wayland.AppImage               
/usr/lib64/pipewire-0.3/jack/libjack.so.0
/lib64/libnss3.so
QEventLoop: Cannot be used without QApplication
QEventLoop: Cannot be used without QApplication
Warning: Ignoring XDG_SESSION_TYPE=wayland on Gnome. Use QT_QPA_PLATFORM=wayland to run on Wayland anyway.
qt.qpa.plugin: Could not load the Qt platform plugin "wayland" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, xcb.

/tmp/.mount_MuseScYQ2xEe/AppRun: line 26:  9206 Aborted                 (core dumped) "${APPDIR}/bin/mscore-portable" "$@"
```

**Comment by AntonioBL** [comment]
@Microwave-WYB : thank you for testing. You can try to set also the env variable QT_DEBUG_PLUGINS:
`export QT_DEBUG_PLUGINS=1`
 before launching the AppImage. It should give more information on why it fails to load the "wayland" plugin.

Ciao,
ABL

**Comment by p-mitana** [comment]
Hello, what is the status of this issue?

Actually, major Linux distributions currently use Wayland by default, which renders MuseScore not working at all currently. Those more tech-savvy may attempt relogging to X session and try then, but that's not what should be required.

Currently updating to stable MuseScore 4 makes the application not starting at all for most Linux users, so in my opinion this should definitely a top priority stability issue.

**Comment by crispyricepc** [comment]
> Hello, what is the status of this issue?
> 
> Actually, major Linux distributions currently use Wayland by default, which renders MuseScore not working at all currently. Those more tech-savvy may attempt relogging to X session and try then, but that's not what should be required.
> 
> Currently updating to stable MuseScore 4 makes the application not starting at all for most Linux users, so in my opinion this should definitely a top priority stability issue.

This shouldn't be the case. Qt will choose the best available platform (in the case of MuseScores appimage, this is xcb), which runs fine on XWayland. The only case that musescore would fail to launch is by having QT_QPA_PLATFORM set to something other than xcb, or your -platform flag is being passed

**Comment by p-mitana** [comment]
> This shouldn't be the case. Qt will choose the best available platform (in the case of MuseScores appimage, this is xcb), which runs fine on XWayland

Unfortunately it is the case. At least on Fedora 37 with GNOME 43 and NVidia drivers. It tries to start, but window is black and the application is not usable at all. I have to relog to X to use the program.

Actually with 3.6 I had serious flickering issues while running with XWayland, but setting the QT_QPA_PLATFORM=wayland made it work better (still not without issues though). For 4.0 none of the options works.

I tried the Flatpak version where I can set QT_QPA_PLATFORM=wayland, but the application fails to start anyway.

**Comment by crispyricepc** [comment]
> Actually with 3.6 I had serious flickering issues while running with XWayland, but setting the QT_QPA_PLATFORM=wayland made it work better (still not without issues though). For 4.0 none of the options works.

I also use an Nvidia GPU and had the same issues with 3.6. But this is an issue with Nvidia drivers and XWayland across most apps, not just musescore (it's why I made the request to include Wayland in the appimage).

> I tried the Flatpak version where I can set QT_QPA_PLATFORM=wayland, but the application fails to start anyway.

Again, I suspect Nvidia drivers are to blame. On my machine, any hardware accelerated Qt completely crashes on Wayland. I think the reason this didn't happen on 3.6 is because they were using the software rendered QtWidgets instead of GPU accelerated QtQuick. But that assumption mostly comes from my experience with working on Qt applications in my own time

**Comment by Ocawesome101** [comment]
The Nvidia suspicion seems pretty reasonable here given that MuseScore 4 works quite well on Wayland for me, sans #15285.

**Comment by p-mitana** [comment]
Yes, most likely this is the case.

Maybe it still could be looked into and fixed somehow? MU3.6 had some glitches, but it was usable on this configuration.

**Comment by crispyricepc** [comment]
For what it's worth, an Nvidia update has fixed the accelearted Qt issue.

The AppImage still doesn't include the necessary libraries for Wayland though, although it's less of an issue for most people as the distros have updated MuseScore in the repos anyway.

**Comment by danielzgtg** [comment]
I tried running MuseScore 4 after building from cmake. That allowed it to choose wayland. All the menus appear in the wrong position:

![image](https://user-images.githubusercontent.com/25646384/217955436-5a1c5bac-2e3f-438d-be41-6985da516447.png)

This is on a 200% hidpi screen. Wayland probably works on a regularly sized screen. A year ago this problem plagued all of the apps on my computer. Input methods, KDE apps, and Anki all showed their overlay menus in the wrong position, but they fixed them problem after a few updates. Perhaps MuseScore needs to find and include the fix.

The whole reason I was investigating Wayland is because the font and icon sizes were unusably small on X11. I ended up fixing the problem in X11 and using it instead, by using `QT_QPA_PLATFORM=xcb QT_SCALE_FACTOR=2 builds/Linux-Qt-usr-Make-Release/install/bin/mscore` or `QT_SCALE_FACTOR=2 ./MuseScore-4.0.1.230121751-x86_64.AppImage`. I have "Legacy Applications (X11): Apply scaling themselves" in KDE5 Display Configuration. `QT_SCALE_FACTOR=2` must not be set system-wide or else that'll cause Qt apps that support Wayland to be too big.

**Comment by crispyricepc** [comment]
> I tried running MuseScore 4 after building from cmake. That allowed it to choose wayland. All the menus appear in the wrong position

Issue is known, see #15285

**Comment by raffaem** [comment]
@RomanPudashkin looks like despite #13781 Wayland plugin is still not bundled in the AppImage?

I'm getting this:
```
➜  QT_QPA_PLATFORM=wayland QT_QPA_PLATFORMTHEME=qt5ct ./MuseScore-Studio-4.3.2.241630832-x86_64.AppImage 
/usr/lib/libjack.so.0
/usr/lib/libnss3.so
qt.qpa.plugin: Could not find the Qt platform plugin "wayland" in ""
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: offscreen, xcb.

/tmp/.mount_MuseScjluC6p/AppRun: line 26: 46403 Aborted                 (core dumped) "${APPDIR}/bin/mscore4portable" "$@"
```

**Comment by cbjeukendrup** [comment]
In 4.2, the wayland plugin was packaged, but we undid that for 4.3 because it turned out to cause problems: because of a version incompatibility between this plugin and some library from wayland itself (I don't remember the details), MuseScore would crash. So we reverted it, because running with xcb is at least better than not running at all. 
We still hope to fix this in the future. I seem to recall that dropping support for Ubuntu 20.04 might facilitate that, but it might still be too early to do that.

**Comment by raffaem** [comment]
> In 4.2, the wayland plugin was packaged, but we undid that for 4.3 because it turned out to cause problems: because of a version incompatibility between this plugin and some library from wayland itself (I don't remember the details), MuseScore would crash. So we reverted it, because running with xcb is at least better than not running at all. We still hope to fix this in the future. I seem to recall that dropping support for Ubuntu 20.04 might facilitate that, but it might still be too early to do that.

Oh I see.

I obtain flickering issues with xcb.

I downloaded the latest nightly builds where the wayland seems to be present, but it crashes indeed.

**Comment by raffaem** [comment]
@cbjeukendrup So, since this bug report is closed, this is now tracked by #20550 right?

**Comment by cbjeukendrup** [comment]
I'll reopen this issue. That should actually have been done directly after merging https://github.com/musescore/MuseScore/pull/20391.
It's also somewhat covered by https://github.com/musescore/MuseScore/issues/21528, but also not entirely, so I think it's good to have this issue open.

**Comment by cbjeukendrup** [comment]
This should be fixed in 4.4 (RC downloadable at https://musescore.org/en/node/367322). The Wayland platform plugin is packaged with the AppImage again, _and_ the crash that happened with it (that was the reason for not packaging it in 4.2 and 4.3) was fixed in https://github.com/musescore/MuseScore/pull/24111. Could you please try it out and let us know your findings? Thanks!

**Comment by raffaem** [comment]
> This should be fixed in 4.4 (RC downloadable at https://musescore.org/en/node/367322). The Wayland platform plugin is packaged with the AppImage again, _and_ the crash that happened with it (that was the reason for not packaging it in 4.2 and 4.3) was fixed in #24111. Could you please try it out and let us know your findings? Thanks!

It seems to work although it's not the standard platform.

You have to run it with

```
QT_QPA_PLATFORM=wayland ./MuseScore-Studio-4.4.0.242351127-x86_64.AppImage 
```

Otherwise it starts under XWayland.

Many thanks for the great work.

**Comment by raffaem** [comment]
I get a bunch of errors in the log:

```
➜  QT_QPA_PLATFORM=wayland ./MuseScore-Studio-4.4.0.242351127-x86_64.AppImage 
/usr/lib/libjack.so.0
/usr/lib/libnss3.so
/usr/lib/libwayland-client.so.0
qt.qml.typeregistration: Invalid QML element name "IconCode"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MusicalSymbolCodes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ContainerType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "NavigationEvent"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MUAccessible"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CompareType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SelectionMode"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ToolBarItemType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "DockToolBarAlignment"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Location"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CloudVisibility"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SaveToCloudResponse"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "DirectionTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SlurTieTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "NoteHead"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Beam"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Hairpin"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "OrnamentTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Dynamic"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Glissando"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CommonTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "BarlineTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MarkerTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "KeySignatureTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "AccidentalTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "FretDiagramTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "LineTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TextTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ArticulationTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "AmbitusTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ChordSymbolTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "BendTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TremoloBarTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TremoloTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "VoiceTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "InstrumentsTreeItemType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "StandardButton"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SaveLocationType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "GenerateAudioTimePeriodType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MigrationType"; value type names should begin with a lowercase letter
16:29:23.885 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /home/raffaele/.local/share/MuseScore/MuseScore4/logs/MuseScore_240823_162923.log
16:29:23.885 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore Studio 4.4.0, build: 242351127 ===
16:29:23.893 | INFO  | main_thread     | LanguagesService::effectiveLanguageCode | System language code: "en-US" 
16:29:23.900 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
16:29:23.900 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
16:29:23.901 | INFO  | main_thread     | IpcSocket::connect | success connected to ipc server
16:29:23.902 | INFO  | 129451100735168 | IpcServer::listen | id: "25af5217ab6747adbbc4034ebab5ac3d" 
16:29:23.974 | INFO  | main_thread     | DiagnosticsModule::onInit | success start crash handler
16:29:24.039 | INFO  | main_thread     | MuseSamplerResolver::doInit | MuseSampler successfully inited: /home/raffaele/.local/share/MuseSampler/lib/libMuseSamplerCoreLib.so
16:29:24.040 | WARN  | main_thread     | Qt              | QIODevice::read (QFile, "/home/raffaele/.local/share/MuseScore/MuseScore4/shortcuts.xml"): device not open
16:29:24.040 | WARN  | main_thread     | Qt              | QIODevice::read (QFile, "/home/raffaele/.local/share/MuseScore/MuseScore4/midi_mappings.xml"): device not open
16:29:24.071 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /home/raffaele/.local/share/MuseScore/MuseScore4/musescorecom_cred.dat
16:29:24.071 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /home/raffaele/.local/share/MuseScore/MuseScore4/audiocom_cred.dat
16:29:24.418 | ERROR | main_thread     | WorkspaceManager::findWorkspaceFiles | [401] The file does not exist
16:29:24.418 | WARN  | main_thread     | WorkspaceManager::setupDefaultWorkspace | not found default workspace, will be created new
16:29:24.702 | WARN  | main_thread     | Qt              | QQmlEngine::setContextForObject(): Object already has a QQmlContext
16:29:24.723 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"

16:29:24.723 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"
16:29:24.724 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"

16:29:24.724 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/internal/PopupContent.qml:81:5: QML QQuickItem: Binding loop detected for property "implicitWidth"
16:29:24.739 | WARN  | main_thread     | Qt              | Dropping not implement for QtQuick on Wayland yet!
16:29:24.747 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.747 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.747 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.747 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.748 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.748 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.748 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.748 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.748 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.748 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.748 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.748 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.749 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.749 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.749 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.749 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.749 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

16:29:24.749 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
16:29:24.765 | ERROR | main_thread     | ExtensionsConfiguration::manifestConfigs | failed read config data, err: [406] An error occurred when reading from the file, file: /home/raffaele/.local/share/MuseScore/MuseScore4/plugins/plugins.json
16:29:24.766 | ERROR | main_thread     | AppShellConfiguration::sessionProjectsPaths | [401] The file does not exist
16:29:26.264 | ERROR | main_thread     | UpdateScenario::doCheckForUpdate | Unable to check for update, error: [1701] 
16:29:26.796 | WARN  | main_thread     | Qt              | QQmlComponent: Created graphical object was not placed in the graphics scene.
16:29:27.693 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: file-open
16:29:27.693 | INFO  | main_thread     | ProjectActionsController::openProject | Try open project: url = "" , displayNameOverride = "" 
16:29:27.696 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/Ui/InteractiveProvider.qml:179: Error: Cannot assign to non-existent property "selectExisting"
16:29:30.280 | ERROR | main_thread     | AppShellConfiguration::sessionProjectsPaths | [401] The file does not exist
16:29:30.463 | ERROR | main_thread     | ScoreThumbnailLoader::loadThumbnail | Could not load thumbnail for "/home/raffaele/Downloads/Led Zeppelin - Stairway To Heaven.gp5" : [21] [21] 
16:29:30.468 | ERROR | 129450475783872 | SynthResolver::resolveSynth | invalid audio source params for trackId: 0
16:29:30.492 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
16:29:30.493 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
16:29:30.515 | ERROR | 129450475783872 | SynthResolver::resolveSynth | invalid audio source params for trackId: 1
16:29:30.517 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
16:29:30.517 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.543 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.543 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.543 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.543 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.543 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.543 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.543 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.543 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
16:29:30.577 | ERROR | 129450475783872 | SynthResolver::resolveSynth | invalid audio source params for trackId: 3
16:29:30.578 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
16:29:30.579 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.629 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.629 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
16:29:30.656 | ERROR | 129450475783872 | SynthResolver::resolveSynth | invalid audio source params for trackId: 6
16:29:30.658 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
16:29:30.658 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.751 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.751 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.751 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.751 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.751 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:30.751 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
16:29:30.774 | ERROR | 129450475783872 | SynthResolver::resolveSynth | invalid audio source params for trackId: 8
16:29:30.775 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
16:29:30.775 | INFO  | 129450475783872 | FluidSynth::addSoundFonts | success load soundfont: /tmp/.mount_MuseScPRPHTN/share/mscore4portabletesting-4.4/sound/MS Basic.sf3
16:29:42.372 | WARN  | main_thread     | Qt              | Wayland does not support QWindow::requestActivate()
16:29:42.373 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:150: ReferenceError: popup is not defined

16:29:42.373 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:150: ReferenceError: popup is not defined
16:29:43.965 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:157: TypeError: Cannot assign to read-only property "openedPopup" (exception occurred during delayed function evaluation)

16:29:43.965 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:157: TypeError: Cannot assign to read-only property "openedPopup" (exception occurred during delayed function evaluation)
16:29:45.556 | WARN  | main_thread     | Qt              | Wayland does not support QWindow::requestActivate()
16:29:45.557 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:150: ReferenceError: popup is not defined

16:29:45.557 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:150: ReferenceError: popup is not defined
16:29:54.543 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:157: TypeError: Cannot assign to read-only property "openedPopup" (exception occurred during delayed function evaluation)

16:29:54.543 | WARN  | main_thread     | Qt              | qrc:/qml/MuseScore/InstrumentsScene/internal/InstrumentsTreeItemDelegate.qml:157: TypeError: Cannot assign to read-only property "openedPopup" (exception occurred during delayed function evaluation)
16:29:57.334 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: play
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.338 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.338 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.338 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.338 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.338 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.338 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.339 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.339 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.363 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.363 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.365 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.365 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.365 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.365 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.365 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
Ending previous ranged articulation, but no 'end ranged' call occurred!
16:29:57.365 | ERROR | 129450475783872 | MuseSamplerSequencer::addNoteEvent | Unable to add event for track
16:30:20.824 | INFO  | main_thread     | ActionsDispatcher::dispatch | try call action: play
16:30:21.673 | WARN  | main_thread     | Qt              | Wayland does not support QWindow::requestActivate()
16:30:21.693 | WARN  | 129450085713600 | Qt              | Could not create EGL surface (EGL error 0x3000)

16:30:21.722 | WARN  | 129450085713600 | Qt              | Could not create EGL surface (EGL error 0x3000)

16:30:21.722 | WARN  | 129450085713600 | Qt              | The Wayland connection experienced a fatal error: Protocol error
[ble: exit 1][ble: elapsed 58.379s (CPU 31.1%)] QT_QPA_PLATFORM=wayland ./MuseScore-Studio-4.4.0.242351127-x86_64.AppImage 
```

**Comment by MarcSabatella** [comment]
Try running with -F to clean up your settings (similar but more "official" way of doing the "rm" that is also more thorough), then see if the problem returns

**Comment by raffaem** [comment]
> Try running with -F to clean up your settings (similar but more "official" way of doing the "rm" that is also more thorough), then see if the problem returns

Still doesn't work even with the `-F` argument.

I have to manually delete the folder:

```
❯ QT_QPA_PLATFORM=wayland ./MuseScoreNightly-latest-master-x86_64.AppImage -F
/usr/lib/libjack.so.0
/usr/lib/libnss3.so
/usr/lib/libOpenGL.so.0
qt.qml.typeregistration: Invalid QML element name "IconCode"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MusicalSymbolCodes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ContainerType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "NavigationEvent"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MUAccessible"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CompareType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SelectionMode"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ToolBarItemType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "DockToolBarAlignment"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Location"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CloudVisibility"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SaveToCloudResponse"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "DirectionTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SlurTieTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "NoteHead"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Beam"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Hairpin"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "OrnamentTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Dynamic"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "Glissando"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "CommonTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "BarlineTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MarkerTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "KeySignatureTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "AccidentalTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "FretDiagramTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "LineTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TextTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ArticulationTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "AmbitusTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "ChordSymbolTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "BendTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TremoloBarTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "TremoloTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "VoiceTypes"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "InstrumentsTreeItemType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "PanelMode"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "StandardButton"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "SaveLocationType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "GenerateAudioTimePeriodType"; value type names should begin with a lowercase letter
qt.qml.typeregistration: Invalid QML element name "MigrationType"; value type names should begin with a lowercase letter
17:32:31.546 | INFO  | main_thread     | GlobalModule::onPreInit | log path: /home/raffaele/.local/share/MuseScore/MuseScore4Development/logs/MuseScore_240928_173231.log
17:32:31.546 | INFO  | main_thread     | GlobalModule::onPreInit | === Started MuseScore Studio Development 4.5.0, build: 242720306 ===
17:32:31.552 | INFO  | main_thread     | LanguagesService::effectiveLanguageCode | System language code: "en-US" 
17:32:31.559 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
17:32:31.559 | WARN  | main_thread     | IpcSocket::connect | failed connect to server
17:32:31.560 | INFO  | main_thread     | IpcSocket::connect | success connected to ipc server
17:32:31.560 | INFO  | 127196008023744 | IpcServer::listen | id: "e663ee0754c347a19b55adb268e36366" 
17:32:31.644 | INFO  | main_thread     | DiagnosticsModule::onInit | success start crash handler
17:32:31.703 | INFO  | main_thread     | MuseSamplerResolver::doInit | MuseSampler successfully inited: /home/raffaele/.local/share/MuseSampler/lib/libMuseSamplerCoreLib.so
17:32:31.703 | WARN  | main_thread     | Qt              | QIODevice::read (QFile, "/home/raffaele/.local/share/MuseScore/MuseScore4Development/shortcuts.xml"): device not open
17:32:31.704 | WARN  | main_thread     | Qt              | QIODevice::read (QFile, "/home/raffaele/.local/share/MuseScore/MuseScore4Development/midi_mappings.xml"): device not open
17:32:31.729 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /home/raffaele/.local/share/MuseScore/MuseScore4Development/musescorecom_cred.dat
17:32:31.729 | WARN  | main_thread     | AbstractCloudService::readTokens | Could not find the tokens file: /home/raffaele/.local/share/MuseScore/MuseScore4Development/audiocom_cred.dat
17:32:32.091 | INFO  | main_thread     | GuiApp::perform | Using graphics api: "opengl" 
17:32:32.094 | INFO  | main_thread     | GuiApp::perform | Detecting problems with graphics api
17:32:32.375 | WARN  | main_thread     | Qt              | QQmlEngine::setContextForObject(): Object already has a QQmlContext
17:32:32.410 | WARN  | main_thread     | Qt              | Dropping not implement for QtQuick on Wayland yet!
17:32:32.417 | WARN  | main_thread     | AbstractMenuModel::makeMenuItem | not found action: manage-plugins
17:32:32.417 | WARN  | main_thread     | AbstractMenuModel::makeMenuItem | not found action: extensions-show-apidump
17:32:32.418 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.418 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.419 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.419 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.419 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.419 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.419 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.419 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.420 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.420 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.420 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.420 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.420 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.420 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.420 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.420 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.421 | ERROR | main_thread     | GuiApp::perform | error: qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"

17:32:32.421 | WARN  | main_thread     | Qt              | qrc:/qml/Muse/UiComponents/FlatButton.qml:182:5: QML Loader: Binding loop detected for property "itemImplicitWidth"
17:32:32.449 | ERROR | main_thread     | ExtensionsConfiguration::manifestConfigs | failed read config data, err: [406] An error occurred when reading from the file, file: /home/raffaele/.local/share/MuseScore/MuseScore4Development/plugins/plugins.json
17:32:32.489 | WARN  | main_thread     | Qt              | Wayland does not support QWindow::requestActivate()
17:32:32.532 | INFO  | main_thread     | GuiApp::perform | No problems detected with graphics api
17:32:32.538 | WARN  | 127194214958784 | Qt              | Could not create EGL surface (EGL error 0x3000)

17:32:32.550 | WARN  | 127194214958784 | Qt              | Could not create EGL surface (EGL error 0x3000)

17:32:32.550 | WARN  | 127194214958784 | Qt              | The Wayland connection experienced a fatal error: Protocol error
[ble: exit 1]
```

**Comment by cbjeukendrup** [comment]
What happens probably, is that when closing MuseScore, a crash would occur, and then when opening it again, a "do you want to restore the session" dialog appears, and the appearance of that dialog causes another crash. 

This seems more likely to be a Qt bug than a MuseScore bug. In the Qt bug tracker, I see some issues that might or might not be related; some of them would be fixed in Qt 6.2.9. You can try a Qt 6.2.9 build of MuseScore here: #24644 
That build has other problems, so we can't release it, but it would be good to know if it does fix this problem.

If not, another option is that it is caused by some missing library. You could run `./MuseScoreNightly-latest-master-x86_64.AppImage check-depends | musescore_deps.txt`, and upload the resulting `musescore_deps.txt` here.

**Comment by ankkax** [comment]
I ran tried the 6.2.9 build I get same issue as raffaem, i Did check depends [](https://pastebin.com/chaL7Fm3)

**Comment by cbjeukendrup** [comment]
The check depends output looks right... so we'll have to continue searching for the problem.

I found somewhere on the internet that setting `QT_DEBUG_PLUGINS=1` in the environment might reveal more useful log output. Could you try that?

There is also a chance that it is solved in Qt 6.8. You can try this experimental Qt 6.8 build: #25016 
(see [How to download test builds from pull requests](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests))

**Comment by ankkax** [comment]
I ran `QT_DEBUG_PLUGINS=1 ./MuseScore-Studio-4.4.3.242670131-x86_64.AppImage check-depends > musescore_deps.txt` for 6.2.9 build

https://pastebin.com/rTi1p14b

and also tried to start mscore with

QT_DEBUG_PLUGINS=1 ./MuseScore-Studio-4.4.3.242670131-x86_64.AppImage -platform wayland

https://pastebin.com/YtLPgWnn


I don't know how to download from #25016 because there is 0 checks, unless I just pull the repo and build it.

**Comment by cbjeukendrup** [comment]
Unfortunately those logs also don't help...

Sorry about the "0 checks"; that is a GitHub bug that occurs a few times per year. I did another push to that PR and now it should be better. Here's a direct link to the download page: https://github.com/musescore/MuseScore/actions/runs/11428448318

**Comment by ankkax** [comment]
oh nice thank you, it just works. And runs natively on wayland and menus are not spawning on the middle, I can finally scale it correctly :+1: .  Also I was curious what happens if I use `-platform wayland`
It doesn't launch.

**Comment by cbjeukendrup** [comment]
> Also I was curious what happens if I use `-platform wayland`
> It doesn't launch.

Do you mean that if you run 4.4.2 with `-platform wayland`, then 4.4.2 doesn't launch?
Or did you mean this for the Qt 6.8 build?

**Comment by ankkax** [comment]
for 6.8 build. I guess I doesn't matter because it now launches on wayland without that option.

**Comment by cbjeukendrup** [comment]
Ah okay. I suspect it has to do with how we parse command line options. If you set the `QT_QPA_PLATFORM=wayland` environment var, does it launch then?

**Comment by ankkax** [comment]
> Ah okay. I suspect it has to do with how we parse command line options. If you set the `QT_QPA_PLATFORM=wayland` environment var, does it launch then?

yes.

**Comment by cbjeukendrup** [comment]
Good to know. Then we'll fix the command line options parsing before the 4.5 release. But I'm glad to hear that the Qt 6.8 update has positive results so far!
