### ISSUE TITLE
[MU4 Issue] Muse Sounds transitions smoothly between dynamics, even without crescendos/decrescendos

### ISSUE THREAD

**Issue by erinic04** [musescore/MuseScore#13902]
**Describe the bug**
Muse Sounds transitions smoothly into new dynamics, even when it is not specified, or even if specifically specified not to (subito)

**To Reproduce**
1. Make new score
2. Make one whole note at pp, one note at ff
3. Hear crescendo, even though there isn't one written

**Expected behavior**
There should not be a crescendo

**Screenshots**
In context:

https://user-images.githubusercontent.com/21023353/197378736-98744d5b-5a9b-4ba8-8594-68119826c089.mp4

Isolated:

https://user-images.githubusercontent.com/21023353/197378827-2690c94e-ac04-43c9-9795-f08f7fcf3a27.mp4

**Platform information**
 - OS: [e.g. macOS, Windows, Linux]

**Additional context**

**Comment by Tantacrul** [comment]
Here is a (slightly amusing) example of how a user suffered from this problem:
https://github.com/musescore/MuseScore/issues/14378

**Comment by LuisLiszt** [comment]
I wonder why this is not a critical problem, I think it is one of the biggest problems MS4 has right now.

**Comment by Tantacrul** [comment]
> I wonder why this is not a critical problem, I think it is one of the biggest problems MS4 has right now.

It's in our release project, so I don't see much reason for complaint. With the latest changes to the Muse Sampler, (which requires the Muse Hub to be opened), it's working for me.

**Comment by MarcSabatella** [comment]
It *is* considered a critical problem, and should have been fixed in the update a few hours ago.  I tested and it works fine for me now.  @mccoydtromb , have you verified you have the currently build and the current muse sampler?  If so, can you please share the score that demonstrates the problem?

**Comment by Tantacrul** [comment]
> Responding to the request to test - still a problem for me. Win 10.

Can you go to your Diagnostic menu and tell me what version number of MuseSampler you have?

<img width="351" alt="image" src="https://user-images.githubusercontent.com/21022311/204663063-0ac4aab4-9202-4ca2-a01a-8d1cda3a858e.png">

**Comment by erinic04** [comment]
I am having problems with this score - also yes, I have the MuseSampler 0.3.0
[Super Mario Galaxy.mscz.zip](https://github.com/musescore/MuseScore/files/10119924/Super.Mario.Galaxy.mscz.zip)
(specifically the second measure in the parts that go to mp)

**Comment by MarcSabatella** [comment]
I can confirm this on that particular score.  After some experimentation, I think I found the trigger - it's the rest on beat 1 of the second measure of the phrase.

Check out the following simplified excerpt:

https://user-images.githubusercontent.com/1799936/204857903-ed86b8cb-d9d5-4386-b71b-f2e5984fe199.mp4

The first phrase plays as expected (except the final ppp note gets swallowed by the tail of the previous note, perhaps the reverb?).  The second phrase show a suddent unexpected change in sound between the first & second bar.

**Comment by LuisLiszt** [comment]
@MarcSabatella with the latest nightly and MuseSample 0.3.0: when I rebuild your first staff I can confirm that there is no automatic crescendo/diminuendo like before. However when using Muse Keys and Muse Percussion instruments the issue still persists. It seems fixed for almost every MuseSounds instrument except the ones mentioned. Can you confirm this? @Tantacrul

**Comment by Tantacrul** [comment]
Yes. It still does it for piano. Thanks @LuisLiszt !

@davidwhearn ^

**Comment by LuisLiszt** [comment]
MuseSampler 0.3.1 fixed the issue for MuseKeys!

**Comment by Tantacrul** [comment]
Yes, I can't reproduce anymore.
