### ISSUE TITLE
[MU4 Task] Design Consideration: Changing instrument names in the mixer

### ISSUE THREAD

**Issue by Grim-O** [musescore/MuseScore#14341]
In the current version of MU4, we're unable to change instrument names in the mixer. It would be nice to see the same interface in the mixer that already exists in the instrument tab, or maybe only just the ability to change the name of the instrument in the mixer and probably linking that to the part name.

**Comment by JeffRocchio** [comment]
**I second this request**. For me, most of my scores are for the same instrument - the Mtn Dulcimer. But I have many ensembles for that instrument. So the 'name' in all the mixer channels are all the same - "Mtn Dulcimer." This is in-spite of my having taken the trouble to change all the part names from their default instrument names to names like "Melody," "Harmony," "Bass," etc. 

So to net it out: Ideal would be to have a setting in Preferences to, say, "_Use Part Names in Mixer._" And then to also be able to simply name each channel in the mixer - the way a DAW would let you do that.

**Comment by remi42** [comment]
Same here with current MS version. The bigger problem is, that the mixer name is shown in the head line of the part using place holde $I .

**Comment by manonash** [comment]
The improvements that people are trying to suggest in this area are badly needed, so I'm kind of amazed -- and not in a good way -- that they remain outstanding after so much time. 

Perhaps part of the problem is that few people use the same terms for the various elements at play when talking about them, so that the discussions are regularly confusing. I don't know the proper names to use either, so I'll just invent some and use a labeled screen shot to clarify my references. 

<img width="1355" height="1099" alt="Image" src="https://github.com/user-attachments/assets/a4fc9d58-0a29-4239-b4e1-b581b5238794" />

If I change a "staff label", the change remains unreflected in the track labels. As you can see from the screenshot, it's quite easy for the staff labels and track labels to get wildly out of sync so that it's **very** difficult to find the right mixer track for changing the gain on the instrument featured in a particular staff. It's really maddening!

There's a somewhat similar issue with the Part names; but there, at least, one has a rename option so one can fix anything that isn't to one's liking. The **only** way to fix the track labels in the mixer is to save the score in uncompressed format and edit the XML. That's not so terrible for a software developer, but it's an absurd difficulty to impose upon a normal end user to accomplish something that should be either automatic or drop-dead simple in the UI.

**Comment by remi42** [comment]
Please keep those labels the same. It's annoying.

**Comment by manonash** [comment]
Just discovered that editing the tracknames in the XML is not without major peril. In one score where I'd changed the value of several trackname properties, the score stopped saving new parts that I created. Also, when I tried to export PDFs or MP4s, it appeared to work as usual, but the output files simply never appeared.

I had to recreate the score by creating a new score, adding staffs to make it match the corrupted one, copy/pasting the notes, lyrics, and chord symbols from the corrupted one, re-entering all repeat bars, voltas, and rehearsal marks, and reassigning playback instruments in the mixer.

**Comment by MarcSabatella** [comment]
It's very unlikely that any of that is related.  Not saving parts is probably due to the fact that changes in the Parts window have not always marked the score dirty. Exporting failing silently is probably due to having not specified the filename extension.  If you encounter these problems again, please check to see if that is the cause.  If not, please open a new issue with the score and steps to reproduce the problem.

**Comment by stevage** [comment]
Yes, this is a big source of confusion and frustration for me. It's particularly painful if you add and remove instruments of the same type. You can rename the "staff labels" (using above terminology), but the "track labels" will keep increasing in the order you added them.

In my case I have this:

<img width="300" height="239" alt="Image" src="https://github.com/user-attachments/assets/6cdf8007-353c-438d-98e9-89746fde9489" />

<img width="675" height="199" alt="Image" src="https://github.com/user-attachments/assets/779a7625-6fbe-4ac3-b0bf-2c940549fd26" />

So the "Horn in F 3" in the mixer does not correspond to the Horn 3 part, and it's fiddly to fix it. And there's no way to make a "Horn 3 and 4" track label, so no matter what I'm going to end up with names like "Horn in F 5" and "Horn in F 6"...sigh.

**Comment by manonash** [comment]
> Yes, this is a big source of confusion and frustration for me. It's particularly painful if you add and remove instruments of the same type. You can rename the "staff labels" (using above terminology), but the "track labels" will keep increasing in the order you added them.
> 
> In my case I have this:
> 
> <img alt="Image" width="300" height="239" src="https://private-user-images.githubusercontent.com/678344/622418431-6cdf8007-353c-438d-98e9-89746fde9489.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODQxOTY2NjEsIm5iZiI6MTc4NDE5NjM2MSwicGF0aCI6Ii82NzgzNDQvNjIyNDE4NDMxLTZjZGY4MDA3LTM1M2MtNDM4ZC05OGU5LTg5NzQ2ZmRlOTQ4OS5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDcxNlQxMDA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1lMGExOTNjOGI5NjcyYjlhNmU1OGE0NmIwZDkzZGQxMjU3Yjk3NjUwNjFlZTJhMjZmN2NmYmUxZDE5MjM2ZDk0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.G_Kj1G-NIcy9OusScXUgccYvQA_TgBgkSLluOZfI07M"> <img alt="Image" width="675" height="199" src="https://private-user-images.githubusercontent.com/678344/622418478-779a7625-6fbe-4ac3-b0bf-2c940549fd26.png?jwt=eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3ODQxOTY2NjEsIm5iZiI6MTc4NDE5NjM2MSwicGF0aCI6Ii82NzgzNDQvNjIyNDE4NDc4LTc3OWE3NjI1LTZmYmUtNGFjMy1iMGJmLTJjOTQwNTQ5ZmQyNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjYwNzE2JTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI2MDcxNlQxMDA2MDFaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YzlkOWJmOThiOGE1MjY3NTJhNzc5NWIyMDk0M2M3YmFlOTkzM2I3MzY3ZGVjZTMzMWM0ZjFjM2ZiNzU2ZWJlJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZyZXNwb25zZS1jb250ZW50LXR5cGU9aW1hZ2UlMkZwbmcifQ.m7evW7Io3FNzjMEvrAl_GwU5QE9jSo_YrTn2EVWYLFU">
> So the "Horn in F 3" in the mixer does not correspond to the Horn 3 part, and it's fiddly to fix it. And there's no way to make a "Horn 3 and 4" track label, so no matter what I'm going to end up with names like "Horn in F 5" and "Horn in F 6"...sigh.

Exactly. Similarly, I do a lot of work with multipart vocals, and so end up with Vocal, Vocal 1, Vocal 2, Vocal 3, etc.; but after a few name edits, rejected experiments, staff moves, and the like the order of tracks no longer bears any discernable relationship to the order of staffs (in addition to the tracks being unrelatable to the staffs on the basis of names). 

Synchronization in the order of staves and tracks can be restored by closing and reopening the mixer (I just discovered), so that helps some, but doesn't really make up for the non-synchronization of the names. AND synchronization of the orders should be automatic: if i move a staff in the Layout panel, its position in the mixer should adjust automatically and immediately.

**Comment by manonash** [comment]
> It's very unlikely that any of that is related. Not saving parts is probably due to the fact that changes in the Parts window have not always marked the score dirty. <

So that's still a bug: just unrelated to the XML edits? 

> Exporting failing silently is probably due to having not specified the filename extension. If you encounter these problems again, please check to see if that is the cause. If not, please open a new issue with the score and steps to reproduce the problem. <

You mean, due to not having specified the format I wanted in the Export dialog? I never explicitly specify the file names for the files to be exported. That's an automatic consequence of the Format I choose in the dialog.

In any case, I don't believe that is what happened. After discovering both the PDFs and the MP4s I thought I had created missing, I tried multiple times exporting the PDFs again and couldn't get them to generate even though the process itself gave me no indication of failure.

Having said all of that: the same score is now both exporting PDFs and MP4s just fine. So it could be that Musescore had just gotten itself in a state. Except that I'm certain I closed and reopened the app more than once during my attempts to generate the PDFs after first discovering them missing.

So I can't open any new issue at this point because I don't, at this point, know how to reproduce the problem. I can provisionally accept that it  had nothing to do with the trackname edits, though.

**Comment by MarcSabatella** [comment]
There have been bugs involving changes in Parts not marking the score dirty, yes - see for instance https://github.com/musescore/MuseScore/issues/20698 and https://github.com/musescore/MuseScore/issues/31656.  The latter is listed as still open although I was unable to reproduce so it may actually have been fixed.  I see it was originally reported against 4.4 even though the issue was only opened in January, so there may be some confusion there.  Anyhow, yes, there have been known bugs, some definiteiy fixed already, some possibly not, where in some cases changes in the Parts dialog may not mark the score dirty and thus woon't be saved unless you then make some *other* change.  Pay attention to the asterisk that appears next to the filename on the tab for the score - that is your indication as to whether MuseScore thinks there are pending saves.  If there is no asterisk, then save will do nothing.

The issue with export has to do with the various different file selection dialogs in different versions of different operating systems.  It is *supposed* to be the case that the filename gets filled in with the proper extension automatically.  But in certain combinations of MuseScore and operating system versions, that hasn't always worked correctly, and you'd have to fill in the extension yourself.  Or if you ever edited the name, you might need to be careful not to remove the extension in the process.  It pays to pay attention to that.

Anyhow, if you ever encounter such a problem again, it probably has nothing to do with the edit you made, as really that code isn't connected in any way.  So be sure to report it separately, as it could simply indicate a new case of an unrelated known problem.

**Comment by manolo** [comment]
> The latter is listed as still open although I was unable to reproduce so it may actually have been fixed

@MarcSabatella #31656 still happens in 4.7, follow the issue instructions and it happens like in the video is shown (updated the video in the issue demonstrating it in 4.7.4 windows)

**Comment by MarcSabatella** [comment]
I confirm the bug is still there.  I think I got confused and missed the significance of the part not having generated yet, since the other issue didn't mention that.  Maybe I thought they were just duplicates.

**Comment by stevage** [comment]
Btw just a note for future me and others that it is possible to figure out which mixer instrument part corresponds to a given layout part like this:

1. Select a bar of music in the part that you're looking at
2. That instrument in the Layout panel will become selected
3. The corresponding instrument in the Mixer will now have "M" and "S" buttons enabled, while every other part will have the M greyed out.

**Comment by manolo** [comment]
> Part not generated yet, since the other issue didn't mention that.

@MarcSabatella  updated the issue title. I hope it's clearer now. Actually, I didn't know about generated parts consuming space, not being removable, etc. until I worked on the [PR](https://github.com/musescore/MuseScore/pull/31738) to fix all these issues together.

**Comment by manonash** [comment]
>> The corresponding instrument in the Mixer will now have "M" and "S"
buttons enabled, while every other part will have the M greyed out. <<

For the record, that is not entirely correct as stated. In a piece with
Alto, Clarinet, Guitar, and Piano staffs (as labeled in layout) I selected
a measure on the Clarinet staff. This staff included above it, farther
along in the score from the measure I selected, a few chord symbols, so the
mixer included a track labeled "Chords.Clarinet" along with the one
labeled  "Clarinet".

Both the "Chords.Clarinet" track and the "Metronome" track had "M" toggle
buttons that were both selected AND enabled.

The point is still taken, though. The "Clarinet" track remained the only
one that had *both *the "M" and "S" buttons  enabled.

This could simply be documented in the manual to solve the UI problem. ☺️

**Comment by stevage** [comment]
> This could simply be documented in the manual to solve the UI problem.

Well, that slightly mitigates the problem, but to solve it you really need to be able to set the mixer names to whatever you want - or, more sensibly, just show the part names by default.

(Also, I don't think you can ever solve a UI problem by documentation, but that's a side issue...)

**Comment by manonash** [comment]
> (Also, I don't think you can ever solve a UI problem by documentation, but that's a side issue...)

I was kidding.

**Comment by manolo** [comment]
I have no design skills, I just threw some ideas together with some CSS, so I can take them as a way to expose a couple of ideas, and make the discussion concrete.

I propose to use staff colors in all three mockups because **the colour already exists in the code and nothing uses it**. `Part::color()` is declared with the comment *"user specified color for helping to label parts"*, it is read and written by the file format, and it defaults to a sensible blue, but nothing has drawn it since the MU3 mixer, and there is no UI to set it. It seems ideal for identifying an instrument across the three views: even before any naming change, a colour makes "which strip is this staff" a glance instead of a matching exercise.

### Idea 1:  More fields in the popover the Layout panel gear already opens

<img width="572" height="647" alt="Image" src="https://github.com/user-attachments/assets/031a6d52-aabb-4e72-a735-c38abcfc0c12" />

- **Layout name** is the identity. 
- **Mixer name** and **Part name** repeat it while `Same` is ticked and are editable when it is not (unticked by default). 
- `Replace instrument` becomes a visible instrument row
- A `colour picker` sits next to the name.

### Idea 2. The mixer Name cell becomes editable, and carries the colour

<img width="1505" height="465" alt="Image" src="https://github.com/user-attachments/assets/49f08319-58fb-4a33-8f47-cf622f4eaf07" />

- Click the cell and type, or pick one of the names already used for that instrument, labelled by where it comes from. 
- The Name row is already a coloured band today, so nothing new is added to the strip: it just now gets the part colour.
- Tracks with no instrument behind them, Chords, Metronome and Master, keep their current colours.
- Color can be changed from the label editor
- If `Same` is clicked in the layout it protects it for editing in the mixer

### Idea 3. The Parts dialog gets the same cell

<img width="835" height="584" alt="Image" src="https://github.com/user-attachments/assets/4af9889c-01db-44a0-975d-e5742f7abcd9" />

- Parts generated from one instrument carry that instrument's colour and offer the same suggestions. 
- Parts assembled by hand get a hollow marker and a plain field, because they can be anything: several instruments, a linked tab staff, a rehearsal part with guitar and voice. There is nothing to derive a name from. They are also the only ones that can be deleted, which is why they show a third icon.
- For a better iteraction with actions, instead of a `...` menu, actions are mapped to buttons in the row
- If `Same` is clicked in the layout user cannot edit the label

**Comment by remi42** [comment]
Good work. I'ld like the colors and please use the part names for the mixer. Or at least make the mixer names editable.

PLEASE
