### ISSUE TITLE
[MU4 Issue] Numeric keyboard and standard numeric keys are broken (specific AZERTY?)

### ISSUE THREAD

**Issue by cadiz2** [musescore/MuseScore#15204]
**Describe the bug**
As written in the title, numeric keyboard and standard numeric keys don't respond at all, or under certain circumstances 

**To Reproduce**
1. Create a score for piano (Treble clef) and Guitar Tablature
2. Input notes in the piano staff and try to change note values or/and input rests ("0")  with the numeric keyboard. Result: failure. 
4. Now input notes in the TAB staff
5. Surprise: the numeric keyboard works, I can choose different notes values
6. BUT: try to enter fret numbers with standard numeric keys. New failure. To get a result, I am forced to use letters A for 0, B for 1, C for 2 etc. 

**Expected behavior**
Numeric keyboard and numeric keys work as expected (ie as version 3.6.2)

**Platform information**
 - Windows 10

**Additional context**
I don't know if it's a specific AZERTY keyboard issue. I would say probably because this problem had already appeared when version 3 was released, and a bug report on the French forum confirmed this malfunction. 
Also: https://musescore.org/en/4.0#comment-1153340

**Comment by opjazz** [comment]
The numeric keyboard on Mac OS doesn't work yet.

**Comment by deadwanderer** [comment]
Just downloaded 4.0 and noticed this same thing. Setting note duration using numpad keys no longer works on 4.0. Can still set them using the number keys above the regular keyboard, but this is way less usable than numpad for duration and keyboard for note values.

**Comment by Flying-Roger** [comment]
I noticed the same problem, really blocking for me as I constantly use the keypad when encoding or modifying scores.
After some investigation, I found out that this can simply be solved by exporting the key shortcuts definitions into an xml file and editing it to add add a few definitions, like this one:
    <SC>
        <key>pad-note-2</key>
        <seq>6</seq>
        <seq>Num+6</seq>
    </SC>
Actually, these definitions, like "Num+6", are missing for the pad-note-x definitions, while they are already present for the tab-pad-note-x definitions, for example:
    <SC>
        <key>pad-note-2-TAB</key>
        <seq>Shift+6</seq>
        <seq>Num+6</seq>
    </SC>
I recommend that all these definitions are included in the default shortcuts of the released version of Musescore 4.

**Comment by liferesearcher57** [comment]
Yes, I'm having the same issue. But I was hoping I wouldn't have to go through all of that export xml file etc. Can't they just fix the problem?

**Comment by MarcSabatella** [comment]
Hopefully so, but that could be weeks before there is an update. Meanwhile, you could have your numpad working in one minute using the workaround provided.

**Comment by DmitryArefiev** [comment]
> 5. BUT: try to enter fret numbers with standard numeric keys. New failure. To get a result, I am forced to use letters A for 0, B for 1, C for 2 etc.

@cadiz2 I switched to French keyboard layout and it works together with **Shift**. 
Because without Shift it gives me: **& é " ' ( - è _ ç à**

So what expected result here when using AZERTY keyboard?

**Comment by cadiz2** [comment]
@DmitriArefiev:
I've been using MuseScore since... 8 years, so I can totally contradict you. I strictly NEVER needed to use the Shift key to enter frets 0, 1, 2 etc. with the standard numeric keys (the row above the letters)
I notice, with the latest nightly, for example (from today) that the number pad works again. Unfortunately, still not the standard numeric keys.
See what happens on this GIF: with 3.6.2, everything happens as expected, I type 0, 1, 2, 3 and I get it.
With 4.0.0, nothing happens. Not only does the number not appear, but the navigation (with the right arrow) jumps from one measure to another. 

![Video frets](https://user-images.githubusercontent.com/114975887/212047650-f318565b-5780-44fa-8006-1eeab99cd309.gif)

**Comment by DmitryArefiev** [comment]
@cadiz2 Hm.. Strange. Can you try this build please? https://github.com/musescore/MuseScore/actions/runs/3894243061

**Comment by cadiz2** [comment]
Sorry, I am a user, not a programmer. I don't what to do after downloading this buid. See image (I don't see the "bin" file to open the app.exe)

![build](https://user-images.githubusercontent.com/114975887/212060453-516a3010-faa3-4674-b01e-976d36fb2b98.jpg)
![bin](https://user-images.githubusercontent.com/114975887/212060485-aead1069-7dc8-4f33-804d-f80a0d3c32d7.jpg)

**Comment by Jojo-Schmitz** [comment]
Extract the 7Z file, unpack that, find the exe in the bin directory then

**Comment by cadiz2** [comment]
Okay, it works. Great! 👍
![tablature](https://user-images.githubusercontent.com/114975887/212063153-78b0fc91-ab79-4bab-9746-092f5b4c633c.jpg)
What was the problem (because the symptom was the same when V3 was released)

**Comment by Flying-Roger** [comment]
I noticed that there is a discrepancy between the way detects the numeric keypad while editing a score with respect to what it does while defining shortcuts:
- while defining a shortcut, pressing 0 on the alphanumerical keyboard or pressing 0 on the numeric keypad has exactly the same effect: "0" is recorded for the shortcut.
- while editing a score, pressing 0 on the alphanumerical keyboard does what is defined as "0" in the shortcut xml file, while pressing 0 on the numeric keypath does is not detected as "0", but as "Num+0", thereby requiring a specific definition in the shortcut xml file.
This is a bug : the consequence is that it is impossible to define a shortcut on the numerical keypad via the shortcut definition menu. The workaround is to export the shortcuts in xml, edit the xml to add the Num+x definitions and reimport the xml file.

I see that this topic is noted as "fixed", but I recommend to make sure that the root cause reported here above is also fixed.

**Comment by cadiz2** [comment]
Well, after further testing, I fear there is something other broken, a side effect I guess of the previous fix. 
Indeed, with the latest nightly (f23ceb1):
1.  the numpad and standard numéric keyboard work when using a TAB staff
2. BUT: now, the numpad is again broken when using Standard Staff: but I can change the notes values with the... standard numeric keyboard...! Kind new mess... (:

**Comment by cadiz2** [comment]
I'm reopening this issue, because it still doesn't work. It's still the same behavior (with attached GIF)  described above. When you attached the Shortcuts numpad fix. 4.0.1 #12473, I tried it and it worked. But with the stable version, it never worked, so for a year now. Now that the fix is no longer available, I don't know what to do?

**Comment by Flying-Roger** [comment]
Hi cadiz2,
I also signalled that this topic should not be flagged as "fixed" just because there is a workaround to this bug.
However, I am surprised that my workaround does not work for you.
I imported my xml definition of the shortcuts long ago and it continued to work over the versions; the import/export of shortcuts is still available in the latest version. I just retested with version 4.2.0 that the keypad still works on my PC.
Note that I still use Musescore 3 due to another issue (midi output not working on my PC with Musescore 4)  so I prefer to avoid getting all my mscz files converted to the M4 format and thereby becoming unusable with M3.
So I regularly test new M4 releases but I will not migrate until this is solved; unfortunately, the developpers are not able to reproduce the problem, although a number of users reported it as I did.

**Comment by cadiz2** [comment]
Hi, Thanks for reply. Well, I don't tried your workaround (I quote: _The workaround is to export the shortcuts in xml, edit the xml to add the Num+x definitions and reimport the xml file), and honestly, I am not sure to achieve this. 🙄
Could you attach your XLM file (for shorcuts) ? Thanks.

**Comment by Flying-Roger** [comment]
Here is an export of my shortcuts.
Normally, such file has an xml type, but github refuses to attach such files so I renamed it .txt
You will need to rename the file .xml to see it in the Musescore 4 import menu.

[Shortcuts Musescore 4 - RogerF.txt](https://github.com/musescore/MuseScore/files/13785734/Shortcuts.Musescore.4.-.RogerF.txt)

**Comment by cadiz2** [comment]
MuseScore 4 import menu? Which menu?

**Comment by Jojo-Schmitz** [comment]
Edit > Preferences > Shortcuts > Import

**Comment by cadiz2** [comment]
I've converted the .txt file to .xml. Then import the file in Preferences/shortcuts. Unfortunately, nothing changes for tablature entry. The numbers on the alphanumeric keyboard refuse to work, unless I use the Shift key as well. It's so annoying and cumbersome that I'm fed up...
And I still don't understand why it worked once (with the file mentioned above, 'Shorcuts numpad fix 4.0.1', but no longer available) and then nothing? I just don't get it.

**Comment by Jojo-Schmitz** [comment]
@Flying-Roger 's fix is about the NumPad, not about the alphanumeric keyboard, as far as I can tell

**Comment by Jojo-Schmitz** [comment]
The PR that closed this issue was also about NumPad, (and NumPad only), it didn't deal with the AZERTY alphanumeric keyboard at all, sho should get reopened to address that

**Comment by cadiz2** [comment]
Ah... 🥺

**Comment by Flying-Roger** [comment]
Sorry for the confusion...
