### ISSUE TITLE
[MU4 Issue] Title frame missing in parts when score create from template containing parts

### ISSUE THREAD

**Issue by MarcSabatella** [musescore/MuseScore#16057]
**Describe the bug**
If you create a template that already contains parts, then scores creates from that template will also already contain parts - but those parts will be missing their title frames

**To Reproduce**
1. Create a score from the string quartet template
2. Create parts
3. Save to your Templates folder
4. Create a new score from your new template
5. View the parts
6. See error: parts are missing the title frame

**Expected behavior**
The parts should have a (linked) copy of the title frame

**Platform information**
 - OS: Linux

**Additional context**
Probably it's not a good idea to create templates with parts, but we can't very well prevent it (unless we implement a special "save as template" command that strips the parts out).  Or we could consider ignoring the parts when creating a score from a template with parts.  But I suppose there are valid use cases for wanting the parts already generated in the template (the ability to have custom parts, part-specific style settings, etc.  So best short term to just fix the title frame bug, I think.

**Comment by Le-Bennou** [comment]
Same here on Windows
- create score with parts from Jazz-Lead-Sheet template
- Adding instruments
- Make some adjustement in styles parameters
- Save in template folder

The title dont show in parts when i create new score from this template, but it's showing when i juste open the file.

I try also to export in non compressed format, put the folder in the main template folder of muscescore and change the categories.json file to add my files, the result is the same.

**Comment by bkunda** [comment]
@mike-spa has this perhaps been fixed in the recent work done on frames in parts?

**Comment by dsayswhat** [comment]
Just popping in to say that I see this bug in my current version of Musescore: 

`OS: Windows 10 Version 2009 or later, Arch.: x86_64, MuseScore version (64-bit): 4.2.1-240230937, revision: github-musescore-musescore-d757433`

**Comment by bkunda** [comment]
Seems like this no longer occurs (possibly fixed indirectly by https://github.com/musescore/MuseScore/pull/19997).

There remains another other issue, where title frames do not contain any text in part scores. I will raise this separately.

**Comment by MarcSabatella** [comment]
I still see this in 4.5, using a template I create in 4.5.  Same steps as shown above.  So, maybe the there was a brief period where the frames got generated and were empty, but now it's back to not frame at all?
