### ISSUE TITLE
Alto saxophone note "A" often doesn't play correctly or at all.

### ISSUE THREAD

**Issue by RexDjere** [musescore/MuseScore#18472]
### Issue type

General playback bug

### Bug description

I'm writing a book of alto saxophone etudes, and I noticed a very frustrating bug. Often, after I play back an etude after writing it, the note A (in the middle of the alto saxophones treble clef) and the A an octave above it do not play correctly. This happens for all variations of A: A, A# and Ab. It seems completely random: sometimes it happens, other times not. Sometimes the higher octave A will sound one octave lower. Sometimes, the middle of the treble clef A won't sound at all. Sometimes the bug appears when you transcribe a score that didn't have the bug to a new key. For example, I transposed an etude from Eb major to F major. In the Eb etude, all of the As played fine. When I transposed it up a step, almost all of the As did not play correctly. I used to try to go through and fix all of the As manually, but this consumes a tremendous amount of time, so I'm going to leave them as is for now, and hope that a MuseScore fix fixes the issue in the future.

### Steps to reproduce

1. Create an alto saxophone score in MuseScore that has the note A, A# or Ab.
2. If you do this enough times, you'll find that, randomly, some note As do not play properly.
3. I have observed this many many times in MuseScore 4.0.2.
4. I don't believe that this happened in MuseScore 3.x.

### MuseScore Version

4.02

### Regression

Choose option...

### Operating system

Pop!OS latest version.

**Comment by MarcSabatella** [comment]
Please attach the specific score with the problem, and say which specific notes (which measure) have the issue.

**Comment by zacjansheski** [comment]
@sammik I think this is the same as https://github.com/musescore/MuseScore/issues/18473

This is reproducible by putting a sharp key sig that switches to flats (I'll share a video in a minute)

**Comment by zacjansheski** [comment]
https://github.com/musescore/MuseScore/assets/69917893/36bac0fb-65af-4a09-ae34-7e4711a2aa3e

**Comment by zacjansheski** [comment]
@RexDjere, Could you confirm that this is the same as https://github.com/musescore/MuseScore/issues/18473
?
Then we will close this and refer to that issue for all transposing instruments.

**Comment by RexDjere** [comment]
@sammik and @zacjansheski: I don't think that it's exactly the same issue because I've experienced it in  amy different keys signatures, and it's always on the notes A, A# or Ab, in the treble clef, or one octave above. I'll post a few example files in a second.

**Comment by RexDjere** [comment]
I wrote this etude today, and this was one of the worst cases I've ever seen: almost every A in the piece didn't play correctly. I went in and manually fixed most of them. How I manually fix? Select the note, use up arrow to raise it a half step, and then down arrow back down a half step. Before I this, clicking on the note, it's doesn't play. After doing this, the note plays when I click on it. Here is a link to the etude: [](https://musescore.com/user/18100066/scores/11392129)
In the linked etude, the Ab in the last measure of line 1 (measure 4), doesn't not play at all when I play the etude in Musescore 4.02. On MuseScore.com, it seems to lay the note, but it doesn't sound right. In measure 17, the Ab5 (the 3rd of 5 motes in the measure) plays an octave too low in MuseScore 4.02. It sounds like it plays 2 octaves too low on MuseScore.com, but I'm not 100% sure: it's definitely doesn't sound right.

**Comment by RexDjere** [comment]
@zacjansheski   Thank you so much!!! I'm hoping to finish the book by this Fall and topublish it on Amazon.com. The music community will probably help me to fix all broken notes in etudes if need be. I eventually plan to publish all 500 etudes on GitHub so that anyone can fix problems and submit pull requests. If MuseScore eventually fixes the problems automatically, that would be awesome!!!

**Comment by RexDjere** [comment]
@zacjansheski  I just watched the video that you posted. Thank you so much!!! I'm going to go through every etude I've written, and fix them if needed using the method that you demonstrated.

**Comment by zacjansheski** [comment]
@RexDjere that method can lead to wrong enharmonics so be careful!  It might be safer to right click an "A" and "Select Same Pitch" then do the up/down trick.

Best of luck, once again, we will work on resolving this ASAP

**Comment by RexDjere** [comment]
@zacjansheski Ah, good to  know....

**Comment by MarcSabatella** [comment]
*In theory* it should be safe with respect to enharmonic spelling to select all, then press Ctrl+up followed by Ctrl+Down - better indeed than up.down.  But this same bug might cause even Ctrl+Up/Down to fail in some cases.  If so, that would be worth knowing about too.

One thing I'm confused about, though - the 234 score plays fine for me in 4.0.2 but not in 4.1, I guess because it is already fixed.  I tried to reproduce from scratch in 4.0.2 starting from 233 but I'm not finding a way.  I see it's set to "prefer flats" in staff/part properties which does indeed seem to connect it to #18473 in that it involves cases where the key signature is flipping between sharps and flats.  But, still, are there really steps to reproduce the proboem in 4.0.2?  Seems that might be good to know, because if so, the problem can't be totally about the new code in 4.1, and it would good to make sure we fix the 4.0.2 case too involving "prefer flats".

Apologies if you guys have already worked this out; I was just want to make sure we're not missing something.  @RexDjere are you sure you see this in 4.0.2 as opposed to pre-release 4.1 builds?  And if so, can you say how to reproduce the problem starting from the 233 score?

**Comment by RexDjere** [comment]
@MarcSabatella Hi Marc!! I've been trying to find other scores with the issue, and I'm having a hard time finding any. I'm starting to suspect that the problem started in a version of MuseScore prior to 4.02. Sometimes I create new etudes by transposing an old etude to a new key. I'm suspecting that the bug may have been in Musescore 4.01 and it carried forward when I transposed the score using 4.02. I've definitely seen the problem many times in 4.02 (which I have been using for weeks). As soon as a find in etude where I can demonstrate the problem in 4.02, I'll post it here. Right now, I'm going through all 234 etudes I've written so far 1 by 1. I've found that another method that appears to work resetting the notes is transposing up an octave, and then down an octave. I'll report back what I find in the next couple of hours.

**Comment by RexDjere** [comment]
@MarcSabatella  I was able to reproduce the problem in MuseScore 4.02 using a new etude that I just wrote. The Ab5 in measure 3 of the score in this video sounds an octave lower than it should.

https://github.com/musescore/MuseScore/assets/1860586/691ae38e-d7d0-48e9-88b6-41797b7af696

**Comment by RexDjere** [comment]
@MarcSabatella I verified that transposing up an octave and then down an octave DOES NOT fix the problem. I'm going to try select all >> CTL+up >> CTL+down next.

**Comment by RexDjere** [comment]
@MarcSabatella  select all >> CTL+up >> CTL+down next DOES NOT fix the problem.

**Comment by RexDjere** [comment]
@MarcSabatella select all >> up >> down next DOES fix the problem, but can change the notation on enharmonic notes.

**Comment by RexDjere** [comment]
@MarcSabatella It looks like select all >> CTL+up >> CTL+down doesn't work because it targets everything selected, including the chords. select all >> up >> down just targets the notes. I think that experimenting with 1.) select all >> up >> down and 2.) select all >> down >> up can sometimes get around the en-harmonic issues. Sometimes 1.) keeps all the notes the same, sometimes 2.) keeps them all the same.

**Comment by MarcSabatella** [comment]
OK, so can you give the steps to reproduce the problem fin 4.0.2, then?  It's possible @zacjansheski and @sammik already have this fully understood, but I'm concerned there is a case that might be missed since the other issue connected to this is definitely only 4.1, so I want to make sure your case is tested as well with any proposed fix.  Ideally you'd have a version of the score that *doesn't* show the problem, and then a list of steps we can follow to cause the problem.  I'm assuming it has something to do with changing key signature, using up/down, and/or Tools / Transpose.

BTW, for the record, there is no difference in what gets affected by Up/Down vs Ctrl+Up/Down.  If the former works but not the latter, it's probably because the latter is "smart" enough not to recalcuate the note name info, just the octave info.  And it's actually the note name info that is (internally) wrong, which is in turn what causes the octave to be wrong on playback even though it displays correctly.

**Comment by RexDjere** [comment]
@MarcSabatella Hi Marc!! It's so random that I really don't know how to reproduce it. It just seems to happen sometimes, and I have no idea why.  Here is my typical workflow in Musescore 4.02:
1.) I open up a brand new file in MuseScore 4.02 and I populate it with only alto saxophone.
2.) I usually make the etude exactly 32 measures long.
3.) I write chord changes for the entire etude.
4.) I write notes for the entire etude.

Sometimes, when I play back the etude for the first time, I noticed that an A, A#, or Ab here and there might not play properly, so I do the control+up then control+down to fix it.

Sometimes, all of the As play fine, but when I transpose the etude to another key, some of the As don't play properly.

I try to add 3 new etudes to my book very day, and the As problem constantly crops up, but I can't tell you exactly when the problem gets created. As I enter each note manually, I try to listen to make sure that I can hear the note as I enter it. But sometimes, I'll copy a passage that I wrote earlier in the etude to another part of the same etude, which means I can't listen to every note as it's entered. It's possible that the problem is introduced when notes are pasted. I'm not really sure how the problem is getting introduced.

**Comment by RexDjere** [comment]
@MarcSabatella I also find it very odd that it ONLY happens with A, A# or Ab. I've NEVER seen it happen with any other note.

**Comment by MarcSabatella** [comment]
That much is consistent with what we know - A for alto saxophone is concert C, which is the change point between octaves in the numbering scheme MuseScore uses for playback (octave 4 is from middle C up to the next B, etc).  So a bug in the internal representation of the pitch can cause the note right at that break to end up playing in the wrong octave.

Anyhow, if you find steps, definitely post them so we can be sure to test that along with the bug we definitely know how to reproduce where your score 234 plays incorrectly in MuseScore 4.1.

**Comment by RexDjere** [comment]
@MarcSabatella Sounds good!!! I'll post re-producible steps as soon as I figure them out. Thank you so much for responding so quickly!!!

**Comment by sammik** [comment]
@RexDjere it should be fixed by #18500 

Please, check it with PR build, if You have some time.

**Comment by RomanPudashkin** [comment]
@RexDjere how's it going? Is it any better? :)

**Comment by RexDjere** [comment]
@RomanPudashkin Hi Roman!!! It looks like MuseScore 4.1 fixed an etude that previously had problems with several As. I'll do more testing, but it looks very good so far.

**Comment by RomanPudashkin** [comment]
Please open a new issue if you find any problems. Thanks!
