### ISSUE TITLE
Crash after changing barline, toggling on/off multi measure rest, Undo all and Redo all

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#19776]
### Issue type

Crash or freeze

### Steps to reproduce

1

### Screenshots/Screen recordings

https://github.com/musescore/MuseScore/assets/90187801/07456292-e6ca-48ab-a750-71ae72ea35fb

### MuseScore Version

4.2.0 master

### Regression

No.

### Operating system

all

**Comment by DmitryArefiev** [comment]
The same in **MS3.6.2**

**Comment by Jojo-Schmitz** [comment]
Actually it dies due to an assertion failure, at least in Mu3, there in segmentlist.cpp, line 135
(https://github.com/musescore/MuseScore/blob/4566605d92467b0f5a36b3731b64150500e48583/libmscore/segmentlist.cpp#L135)

**Comment by sammik** [comment]
I was working on other barline issues, but it seems this one is fixed too in my local build.

**Comment by sammik** [comment]
please test #19783

**Comment by sammik** [comment]
please update steps regarding [#19783 comment](https://github.com/musescore/MuseScore/issues/19783#issuecomment-1772970452_)

**Comment by DmitryArefiev** [comment]
> please update steps regarding [#19783 comment](https://github.com/musescore/MuseScore/issues/19783#issuecomment-1772970452_)

@zacjansheski Can you update please? Thanks!

**Comment by zacjansheski** [comment]
Updated
Diagnostics here:

[UndoRedoCrash.zip](https://github.com/musescore/MuseScore/files/13243190/UndoRedoCrash.zip)

**Comment by DmitryArefiev** [comment]
Fixed in #20331

**Comment by DmitryArefiev** [comment]
> Fixed in #20331

Fix from #20331 is not merged since it's not easy to fix without potential risk as @RomanPudashkin mentioned in https://github.com/musescore/MuseScore/pull/20331#discussion_r1420149649

@bkunda I moving this to 4.3 for now

**Comment by bkunda** [comment]
Moving to 4.4 on advice from dev about potential riskiness inherent in making this fix in 4.3.

**Comment by SilverGreen93** [comment]
I can still reproduce in MuseScore 4.6.0 Windows nightly using these steps:
1. Drag a forward repeat bar to any measure
2. Select the repeat bar and press M
3. Drag a simple measure bar on top of the forward repeat bar
4. Undo all actions until the beginning
5. Redo all actions until it crashes.
