### ISSUE TITLE
"Show Invisible" does not always show invisible lines

### ISSUE THREAD

**Issue by krasko78** [musescore/MuseScore#20662]
### Issue type

Engraving bug (incorrect score rendering)

### Bug description

Opening a score that has "Show invisible" = off, doesn't show crescendo, diminuendo, etc. lines (grayed out) when "Show invisible" is turned on.

### Steps to reproduce

1. Open a score with a crescendo that has "Show line" off and the score doesn't show invisible.
2. Check the "Show invisible" checkbox in the Properties panel.

ACTUAL: The line of the crescendo does not appear.
EXPECTED: The line of the crescendo appears and is gray because "Show line" is off.

Setting "Show line" to ON displays the line not grayed out (this is correct). Setting "Show line" then back to OFF correctly leaves the line visible and grays it out.

### Screenshots/Screen recordings

Here is a screenshot. "Show Invisible" is ON but the line of the crescendo is not visible. In this example, the crescendo spans two systems. In MU4.2 the line is not diplayed in either system, whereas in MU4.1 it is displayed on the SECOND system only but still not for the first system.
![image](https://github.com/musescore/MuseScore/assets/154632626/8488acb3-4a50-41f8-9bd8-2535780a82fa)

### MuseScore Version

4.2

### Regression

No.

### Operating system

Windows 10

### Additional context

Here is a sample score, see measure 66.
[new score.zip](https://github.com/musescore/MuseScore/files/13756598/new.score.zip)

As I said above, this is broken in MU4.1 too, but differently. In MU4.1, the line on the second system is displayed but not on the first. In MU4.2 both are missing. This difference might have something to do with [this bug](https://github.com/musescore/MuseScore/issues/20661)

**Comment by mercuree** [comment]
I think it was fixed here #20590. 
Please, check nightly builds https://ftp.osuosl.org/pub/musescore-nightlies/windows/4x/nightly/

**Comment by mercuree** [comment]
Confirm. [new score.zip](https://github.com/musescore/MuseScore/files/13756598/new.score.zip) also crashed on exit

https://github.com/musescore/MuseScore/assets/919446/df1b8e39-c88e-462a-89c5-969ea7637511

**Comment by oktophonie** [comment]
The lines will show (at least on the first system...) but only after a redraw happens. Sigh.

**Comment by krasko78** [comment]
Just grabbed the latest night build (MuseScoreNightly-latest-4.2.1-x86_64.7z) and the issue is still present.
