### ISSUE TITLE
UI Memory leak

### ISSUE THREAD

**Issue by metasekk** [musescore/MuseScore#23158]
### Issue type

Crash or freeze

### Bug description

Almost all interactions with the UI increase the memory (RAM amount) indefinitely, slowing down the interface progressively. Things have seriously worsened in master 4.4 (Qt6), but the issue occurs in previous versions too.

### Steps to reproduce

Main ways identified to increase the memory (in decreasing order of importance):

1. Open windows ~(e.g. +50 Mb for "Preferences" each time)~
 => EDIT (08/07/24): **Greatly improved in #23495** (**+2 Mb** for each opening/closing cycle instead of +50 Mb).
2. Open menus ~(+20 Mb each time; +1 Mb when closing)~
 => EDIT (08/07/24): **Greatly improved in #23495** (**+0.25 Mb** for each opening/closing cycle instead of +20 Mb).

EDIT (08/07/24): Issues below are **still reproducible** afaik:

3. Click/Hover over submenus (+20 Mb, e.g. "File > Open recent")
4. Move/drag the score (between +1 Mb/s and +10 Mb/s, depending on the movement, and the duration when dragging)
5. Zoom in/Zoom out (~1 Mb for each)
6. Selecting two bars alternately in a score, or selecting one then releasing it by clicking elsewhere (~300 kb each time)
7. Open/close palettes (+10 kb each)

Note that it **only occurs when a score is open**.

### Screenshots/Screen recordings

https://drive.google.com/file/d/1FRGApBrWmJTWLxiq2I-89gA6ICNtWtcY/view?usp=sharing

### MuseScore Version

Tested on **4.4, 4.3.1, 4.2.1 and 4.1.0** (much slower growth in 4.1.0 and 4.2.1, but still present)

### Regression

I don't know

### Operating system

Win10 (22H2); RAM: 16Go; CPU: Intel Core i5-9300H (2.40GHz)

### Additional context

Alongside other identified leaks (e.g. #23112 and #22721), it might partially explain #22094 and #20889.
Reported on musescore.org multiple times (e.g. https://musescore.org/en/node/364227, https://musescore.org/en/node/353935...)

EDIT (07/07/24): Point 2 ("Open menus") item is a duplicate of #22885.

**Comment by zacjansheski** [comment]
Closing as fixed by https://github.com/musescore/MuseScore/pull/23495

Thank you!

**Comment by metasekk** [comment]
Hmm... The situation has clearly improved, but point 3 to 7 still arise, and above all, I believe that point 4 remains really problematic: moving or dragging the score, even with the slightest movement, still increases the RAM by 1-10 Mo each time (just re-checked with latest master including #23495). As a consequence, when editing scores, I still get a typical **~2 Go increase in memory** when using the software for **~1 hour** with latest master. I think that point 4 (memory leak with movements of the score) is one of the main reasons why there were complaints that the software _becomes_ slow on some machines after a rather long period of use (e.g. #22094, https://musescore.org/en/node/364227).

**Comment by bkunda** [comment]
@zacjansheski when you next can, pls check the remaining unticked issues in the description above to verify whether they remain problematic.

**Comment by zacjansheski** [comment]
The memory leak issue is unchanged since last discussion

The click/drag score leak seems to be the biggest problem here (easy to reproduce and leads to a bad experience in long sessions)

**Comment by RomanPudashkin** [comment]
@zacjansheski please log the remaining leaks separately (after https://github.com/musescore/MuseScore/pull/26500)
