### ISSUE TITLE
Slow when adding or insterting a new bar at the end of the score/part

### ISSUE THREAD

**Issue by lorenzogavanna** [musescore/MuseScore#24632]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

1.  Create a score 
2. Add notes and everything you need to engrave
i.e. Five part single staff per part (violin 1, violin 2, viola, alto voice, cello)
Fill the score and than when you get to 25/30 bars the function add/insert bar starts to be very slow. Getting worst adding more elements to the score. With no notes or elements in the score everything is smooth and doesn't have any problem.
P.S. Everything like adding notes and palettes is getting better with the new nightly, but the adding/inserting bar is still buggy and slow in the descripted cases.

### Supporting files, videos and screenshots

[issue.zip](https://github.com/user-attachments/files/16959991/issue.zip)
![issue](https://github.com/user-attachments/assets/4894d86c-219d-47ad-a4e5-fb65b97ac17c)

### What is the latest version of MuseScore Studio where this issue is present?

Always has been there since 4.x and still there in the latest nightly 4.4.1.242481121 studio and hub

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Additional context

This happens with two different machines surface pro 7 i5-1035G4 8gb windows 11
one desktop with AMD Ryzen 5 1600 Six-Core Processor 3.20 GHz RAM installata 16,0 GB windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
Please zip and attach the score that is giving you problems.

**Comment by lorenzogavanna** [comment]
> Please zip and attach the score that is giving you problems.

Actually it happens with any score, but here it i
[004_Amorhaivinto_Allegro.zip](https://github.com/user-attachments/files/16986065/004_Amorhaivinto_Allegro.zip)
s.

**Comment by MarcSabatella** [comment]
Strange, for me it's nearly as slow as it looks in your video - a fraction of a second tops, and my machine is not faster than yours.  But it's certainly true that the larger a score gets, the slower certain operations before - that's kind of unavoidable.

**Comment by lorenzogavanna** [comment]
> Strange, for me it's nearly as slow as it looks in your video - a fraction of a second tops, and my machine is not faster than yours. But it's certainly true that the larger a score gets, the slower certain operations before - that's kind of unavoidable.

Yes, but we are not talking about very big projects, I mean, 30 bars for five voices (in my example).. it's like 150 bars. And in musescore 3 was immediately executing even with very very big files. This should and I think can be avoidable.

**Comment by lorenzogavanna** [comment]
In the latest official release 4.4.2 this is still there. Is thre any reason why the issue has not been assigned to any of the developer, is that something wrong in my description? It's kind of critical.

**Comment by cbjeukendrup** [comment]
> Is thre any reason why the issue has not been assigned to any of the developer

Very concretely, that is because we normally do "triage sessions" on Tuesday and Friday but the one from last Friday was cancelled because of other activities. 

And there are lots of other important issues too, so we cannot suddenly prioritise this immediately, even though we recognise the importance of this issue too.

**Comment by lorenzogavanna** [comment]
> Very concretely, that is because we normally do "triage sessions" on Tuesday and Friday but the one from last Friday was cancelled because of other activities.
> 
> And there are lots of other important issues too, so we cannot suddenly prioritise this immediately, even though we recognise the importance of this issue too.

Thank you for the reply! I just thought it was my fault in some passages! In any case I can ensure that the entire graveing process become slower not only the add bar function. Thank you!

**Comment by lorenzogavanna** [comment]
Hi team, just to add an update: I tried every nightly that you published and the entire Musescore is getting slower while elements things to the score. Little example: 5 voices files
- empty staves, no notes or elements on it, it starts to get slower after 250/260 bars. 
- Same file with notes and elemtents on it , it starts to get slwoer after 30/40 bars.
Hope it helps.

**Comment by lorenzogavanna** [comment]
Hi team, just to add an update: I tried every nightly that you published and the entire Musescore is getting slower while you add elements to the score. Little example with a 5 voices file:
- empty staves, no notes or elements on it--> it starts to get slower after 250/260 bars. 
- Same file with notes and elemtents on it-->, it starts to get slower after 30/40 bars.
Hope it helps.

**Comment by OsePedro** [comment]
I just want to report that I'm experiencing the same issue in both the latest stable build (4.4.3-242971445, revision: github-musescore-musescore-eb6b367) and the latest nightly build (4.4.4-243250401, revision: github-musescore-musescore-c5c81eb). My system specs are:

```
4.00GHz AMD FX(tm)-8350 Eight-Core Processor
16.0 GB RAM
Windows 10 Pro
Steinberg UR-22 audio interface
```

As Lorenzo reported, inserting and deleting bars in Musescore 3 is much faster for me than in Musescore 4 for scores of the size that he stated in his last comment. See the following 27-bar score of strings, woodwind and brass playing scales. Musescore 3 completes bar insertion by the time I've lifted my finger off the insert key, whereas Musescore 4 takes about 2 seconds to insert a bar.

[Orchestral C Scale.zip](https://github.com/user-attachments/files/17838416/Orchestral.C.Scale.zip)

**Comment by OsePedro** [comment]
To be fair, Musescore 4 is much more usable than it used to be. Last year, I wrote a full orchestral score in it that was about 35 bars long, and at a certain point it started taking a couple of seconds to respond every time I tried to add or select a single note. The fact that this has been resolved suggests to me that they are being sensible about how they prioritise usability issues.

Slow bar insertion is annoying, but I can live with it -- I just insert lots of bars at once, so that I can then focus on filling them with music for the next few days.

**Comment by lorenzogavanna** [comment]
I downloaded all the official and nightly versions until 8th October with the score I attached and many others very similar the issue is still there and it's not only the bar insertion problem. Maybe I was wrong putting this title and made them thinking, but I updated the issue with other details.
