### ISSUE TITLE
Changing appearance properties (accent colour/theme) alternately borks, then corrects, button and secondary colours in "old" QWidget dialogs

### ISSUE THREAD

**Issue by bkunda** [musescore/MuseScore#24667]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. Change the UI accent colour in Preferences > Appearance
2. Observe the change in colour behind the app title bar
3. Open Format > Styles
4. Observe how secondary button colours are missing, as well as different colours in the left panel 

### Supporting files, videos and screenshots

[See video](https://drive.google.com/file/d/175Fua6HULrq4yJhAjWhJJQvtATTNGOjd/view?usp=sharing)

### What is the latest version of MuseScore Studio where this issue is present?

4.4.2

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Windows 11, macOS 14.6.1

### Additional context

Occurs since 4.4.0

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by avvvvve** [comment]
https://github.com/user-attachments/assets/86312824-eba0-4df1-ac2d-e6c39e2128f6

Attaching this video of the same behavior in dark mode, where the striping of the left scroll area in Style is more obvious/egregious.

Worth noting that changing between light/dark mode will not cause the borked state, but it will fix it.

**Comment by cbjeukendrup** [comment]
I hardly dare to believe it but this seems fixed in Qt 6.2.9 (#24095). If only I could fix that blocking problem with disappearing texts... then we could just switch on macOS too, and have three issues fixed for free.
Another thing we can try, is whether Qt 6.2.8 doesn't have that text problem but does solve all those issues. That's complete guesswork that can cost us a lot of time though, because we don't have access to release notes of any kind.
We can also hope for the next version, Qt 6.2.10, but that will be open-sourced only from October 9th.

**Comment by FrancRos31** [comment]
I reproduce it and the problem is worse. All the Style dialog loses color.
![Image](https://github.com/user-attachments/assets/026e2e45-4da5-468b-9d94-92aee7f0f0fb)

**Comment by cbjeukendrup** [comment]
On Windows, this should be fixed in the latest nightly builds: 
https://musescore.org/en/nightly-builds

(It's a Qt bug that turned out to be fixed in a later version of Qt, and now the nightly builds for Windows are using that later Qt version.)

**Comment by FrancRos31** [comment]
No, the latest build didn't solve the issue.

https://github.com/user-attachments/assets/8bb50aa1-d1f7-4a6f-b1a0-63279dbb6cbf

**Comment by cbjeukendrup** [comment]
Ah, you got a master (=4.5) nightly build, rather than a 4.4.3 one. Currently, the fix is only in 4.4.3 (yes, that's weird, but there are reasons for that)

**Comment by FrancRos31** [comment]
Shoot, didn't think about it. In 4.4.3 build is solved, thank you!

**Comment by cbjeukendrup** [comment]
Great! Putting it as "done" in 4.4.3, but keeping it open because it needs to be solved on `master` too of course

**Comment by avvvvve** [comment]
@cbjeukendrup just noticed this one again in the Master. Note also that the buttons are missing their backgrounds.

<img width="680" alt="Image" src="https://github.com/user-attachments/assets/27826623-a15d-4f87-8404-c1b306493ce7" />

...and when I focus away from the window the buttons get even more borked.

<img width="684" alt="Image" src="https://github.com/user-attachments/assets/89085f61-34bd-4c4d-af0d-ad8127261924" />
