### ISSUE TITLE
The duration of the notes is shorter with Con sord/Mute

### ISSUE THREAD

**Issue by Dima-S-Jr** [musescore/MuseScore#25353]
### Issue type

General playback bug

### Description with steps to reproduce

See the attached video below.

### Supporting files, videos and screenshots

1. Open [this](https://drive.google.com/file/d/13yDX2Q3OGym6KTuqgFfoIxD5e3Oz220m/view?usp=drive_link) score (or short version [premature stop_short.zip](https://github.com/user-attachments/files/18787207/premature.stop_short.zip) for devs )
2. Make sure that the **MS Basic** audio profile is activated
3. Listen to how French **horns** sound in **bars 19-22**. The sound stops at the 2nd beat of the 21st bar:

https://github.com/user-attachments/assets/ad1efd5e-2638-4df2-a432-ade1b7fe40d9

4. Now listen to how the **cellos** with **double basses** sound in **6-10 bars**. You will hear that the sound stops at the 3rd beat of the 9th bar:

https://github.com/user-attachments/assets/4bbec252-7359-4357-acf8-26b6c9d9a25e

5. Listen to how **violas** with **cellos** sound in **bars 19-23**. You will hear that the sound stops immediately as soon as the cursor reaches the hairpin, the final ending of which is _niente_: 

https://github.com/user-attachments/assets/7a3df309-749f-407c-8254-7701da1be7e7

The sound should not stop so abruptly. Listen, for example, to how smoothly the sound of violins fades out: 

https://github.com/user-attachments/assets/598a5b70-22dd-4f22-8089-178eb0f048b6

6. Then switch to the Muse Sounds sound profile. In strings, the problem of fully holding notes will disappear. But on the other hand, French horns (in bars 19-22) notes will be interrupted even earlier than with MS Basic (the sound will stop in the 2nd bar): 

https://github.com/user-attachments/assets/5fe94d85-4723-4b61-996a-b5f48112c0cb

### What is the latest version of MuseScore Studio where this issue is present?

MuseScore Studio version (64-bit): 4.4.3-242971445, revision: github-musescore-musescore-eb6b367

### Regression

I was unable to check

### Operating system

Windows 11

### Additional context

I have no idea what caused these bugs. But since in one of the cases the sound stops at the moment when the cursor reaches the hairpin, the final ending of which is _niente_, then I suppose this may be similar to the regression coming from #24544 

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by Dima-S-Jr** [comment]
I think I've figured out why the French horns sound stops prematurely. It's because of "mute": 

https://github.com/user-attachments/assets/407ff96f-e628-4126-934c-939d642b521e

As for the strings, I still don't fully understand the cause of the bug.

**Comment by zacjansheski** [comment]
The muted horns in Muse Sounds issue is fixed in latest update

**Comment by Dima-S-Jr** [comment]
So, with the recent update of the Muse Sounds libraries, I no longer see any problems (with the Muse Sounds sound profile). But in MS Basic, the situation remains the same, unresolved. Strings and French horns still do not withstand the full duration of the notes as I outlined in the issue.

**Comment by erinic04** [comment]
#22691 ?

**Comment by Dima-S-Jr** [comment]
I just ran into the same problem. Maybe it will be useful (in cellos, bars 46 to 48 do not sound on an adjacent staff [only MS Basic]). 
[Loose Ends.zip](https://github.com/user-attachments/files/18008581/Loose.Ends.zip)
MuseScore Studio version: 4.5.0-243380315, revision: github-musescore-musescore-20ecf84

**Comment by DmitryArefiev** [comment]
Still occurs after #25187 
(and after #25187 the duration of tied notes even became smaller by several beats)

**Comment by Dima-S-Jr** [comment]
> I just ran into the same problem. Maybe it will be useful (in cellos, bars 46 to 48 do not sound on an adjacent staff [only MS Basic]). [46-48 stopping sound.zip](https://github.com/user-attachments/files/18008581/Loose.Ends.zip) MuseScore Studio version: 4.5.0-243380315, revision: github-musescore-musescore-20ecf84

I just checked in the master version - now it happens with Muse Sounds. (4.5.0-243420313, revision: github-musescore-musescore-154aba2)

**Comment by bkunda** [comment]
@DmitryArefiev could you pls do a regression check on this?

**Comment by DmitryArefiev** [comment]
> I just checked in the master version - now it also happens with Muse Sounds (4.5.0-243420313, revision: github-musescore-musescore-154aba2)

@bkunda @RomanPudashkin Yup.. The same result on my side (4.5 on Win10). With **MuseSounds**, it's a fresh **regression** (**doesn't occur** in **4.4.4**) 

https://github.com/user-attachments/assets/18faf2fc-a87c-421e-95a7-85343dd92118

**Comment by DmitryArefiev** [comment]
Fixed in #26504
