### ISSUE TITLE
Style dialog too big by default; OK/Cancel buttons fall of the screen on smaller screens

### ISSUE THREAD

**Issue by SvendAndersen** [musescore/MuseScore#25457]
### Task

Decrease the default height of the style dialog to 760px.

This will ensure that it's not cut off on a standard small laptop with 1366×768px resolution.

Also, if a user manually resizes the dialog, MuseScore Studio currently recalls its last dimensions even if you quit and restart. So when changing the default, ideally we would _not_ reset the size of the dialog for users who have already manually resized it.

_Edit above by @avvvvve, original issue text below_

-----

### Issue type

Other type of issue

### Description with steps to reproduce

In the new version of Musescore 4 there is an error under Layout, as the Ok button is missing. This means that the choices you have made are not saved and Layout therefore in practice does not exist. Today I completed the latest update, where the error was not fixed. I hope the error will be corrected.
Kind regard
Svend Andersen
Denmark

### Supporting files, videos and screenshots

![image](https://github.com/user-attachments/assets/823ffdbf-83e1-45c1-943a-3caf75bdf147)

### What is the latest version of MuseScore Studio where this issue is present?

Version 4

### Regression

Yes, this used to work in MuseScore 3.x and now is broken

### Operating system

Windows 11

### Checklist

- [X] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [X] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [X] I have attached all requested files and information to this report
- [X] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by MarcSabatella** [comment]
The button is present; your screen resolution just isn't high enough to be showing it.  Resize the dialog to be smaller and it will be visible.

The dialog *is* entirely too big by default, though.  It should be able to fit comfortably on any system using common display resolutions, but it really doesn't.  There are a couple of existing issues that indirectly touch on this - see #21907 and  #24917 - but really, if a full refactor is only a long term goal, we should find a way to make this dialog fit onto more displays, as we get complaints about this quite often in the forums etc.

**Comment by Jojo-Schmitz** [comment]
And it isn't really a Mu3 regression, there too users occasionally complained about this.

**Comment by Jojo-Schmitz** [comment]
Also the dialog can be masde smaller by the users by grepping the top line of the windows and dragging it down, then grabing the title bar and dragging it up, so you can see the buttons at the bottom.

**Comment by avvvvve** [comment]
Added the specification to solve this issue to the top of the description (make the default height 760px), so this is ready for a contributor to take on!

**Comment by SvendAndersen** [comment]
I have now found a temporary solution to the problem by changing the display setting. On my monitor it was set to the recommended 125%. I changed it to 100% and the problem was solved.
Svend Andersen
Denmark

**Comment by avvvvve** [comment]
@SvendAndersen Glad you figured out a fix. I think we should still go ahead and change the default height as I outlined above so that users with small screens don't run into this issue.

**Comment by WhyMeAgain233** [comment]
Is it possible to set the default window height according to the device's resolution or other relevant parameters? I've tried a few resolutions and the issue occurs on 16:9 aspect ratio.

**Comment by Jojo-Schmitz** [comment]
The current default width and height are
https://github.com/musescore/MuseScore/blob/7da2197180797704c1a8b60dd006dbcab3e1f14b/src/notation/view/widgets/editstyle.ui#L9-L10
So height is bigger than 760 (and bigger than in Mu3, where it is 752)

But a _standard small laptop with 1366×768px resolution_ that still won't fit, unless that does get set to 100%, from the usual defaults of 125% or even 150%

**Comment by WhyMeAgain233** [comment]
Hi, I've submitted a pull request that aims to address the issue. The motivation is to check if the EditStyle dialog can be fully displayed according to the current device's screen resolution. If not, it tries to limit the size to an upper bound. I also changed the default height back to 752 in MU3.

However, I'm not entirely sure whether this method is applicable or whether it matches the coding standards, such as introducing a magic number. Also, changing the default height in the .ui file led to a lot of automatic changes done by QtCreator. 

Could you please review my PR and provide feedback on the aforementioned uncertainties? Any guidance or suggestions for improvement would be greatly appreciated. Thank you for your time and consideration.

**Comment by Jojo-Schmitz** [comment]
You could change the UI file in a regular plain text editor instead of QtCreator/QtDesigner

**Comment by WhyMeAgain233** [comment]
Oh, indeed. Can't believe I missed that. 🤦 Is there anything else I could do to improve?
