### ISSUE TITLE
Keyboard input broken for most spin boxes under KDE Plasma + Wayland

### ISSUE THREAD

**Issue by mrbumpy409** [musescore/MuseScore#28866]
### Issue type

UX/Interaction bug (incorrect behaviour)

### Description with steps to reproduce

Most of the spin boxes in MuseScore will not accept keyboard input. This includes the initial number of measures when creating a new score, and all of the spin boxes under "Appearance" settings for any element. Only mouse interaction with the up and down spinner buttons can change the values. The only spin boxes that seem to accept keyboard input are those in options found in the menu, such as "Preferences", "Style", "Page Settings".

I am experiencing this bug using both the current stable release (4.5.2 AppImage) and latest nightly AppImage, which provides the following info:
* OS: Fedora Linux 42 (KDE Plasma Desktop Edition)
* Arch.: x86_64
* MuseScore Studio version (64-bit): 4.6.0-252010330
* revision: github-musescore-musescore-c59aa3b

## Steps to Reproduce
1. Start MuseScore Studio.
2. Start a new score.
3. On the second page where you can set initial number of measures, click on "32 measures, no pickup" and highlight "32" under "Initial number of measures".
4. Attempt to type in a new number of measures.

**Result:** Nothing happens. The backspace key does delete the selected number, but any numbers typed on the keyboard do not appear. This bug can also be reproduced by attempting to edit any of the appearance settings for a notation element (e.g., click a note or whatever, go to the "Properties" tab on the left side of the screen, then click "Appearance"). Unfortunately, this makes many fine positional adjustments impossible as the spinner buttons often only allow large jumps in position.

### Supporting files, videos and screenshots

I don't know how to make a screen capture that would actually be useful.

### What is the latest version of MuseScore Studio where this issue is present?

OS: Fedora Linux 42 (KDE Plasma Desktop Edition), Arch.: x86_64, MuseScore Studio version (64-bit): 4.6.0-252010330, revision: github-musescore-musescore-c59aa3b

### Regression

No

### Operating system

Fedora Linux 42 KDE Plasma Desktop Edition, using Wayland

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by mrbumpy409** [comment]
After further testing, I can provide the following additional context:
* The bug only seems to happen when using KDE Plasma and Wayland. The bug is reproducible when the Fedora 42 KDE or Kubuntu 25.04 Live ISO image in a virtual machine (I'm using virt-manager).
* Using KDE Plasma in X11 mode does not trigger the bug (keyboard input works correctly).
* The bug does not happen in Gnome + Wayland (as tested via the Fedora 42 Workstation Live ISO image).
* The bug also affects the Flatpak version of MuseScore.

**Comment by mrbumpy409** [comment]
I discovered that the version of MuseScore in the Fedora repositories (4.3.2) does not exhibit this bug, while the 4.3.2 AppImage does. However, Fedora's MuseScore package crashes after the last step of creating a new score, so I can't exactly recommend it as a workaround.

**Comment by ghost** [comment]
In 4.6 this also affects the spin boxes in the text editing widget, e.g.:

<img width="1411" height="202" alt="Image" src="https://github.com/user-attachments/assets/750e26f8-09d8-4523-a3cc-be06dffc536f" />

(but, along with the others, this is fixed by https://github.com/musescore/MuseScore/pull/29888)

**Comment by kbloom** [comment]
I just gave this a try with MuseScore 4.6.3 (appimage) under Plasma 6.3.6 Wayland on Manjaro Linux, and observed the following:

MuseScore 4.6.3 overrides QT_QPA_PLATFORM to use the xcb backed, so it's running under XWayland. You can override this by setting the MU_QT_QPA_PLATFORM variable to any non-empty value. See https://github.com/musescore/MuseScore/blob/v4.6.3/src/app/main.cpp, and cc864afd094d49fbe64c0773dee6d21b8a3e3de5 and c8dcdfbe4da7a4ede6bafde34f9dfa1f07b78866. (An aside: I think this latter commit is incorrect, because the specific value of MU_QT_QPA_PLATFORM is ignored by the code.)

If I run MuseScore with QT_QPA_PLATFORM=xcb (the default), you can't type into spin boxes.

If I run MuseScore with QT_QPA_PLATFORM unset by setting MU_QT_QPA_PLATFORM, you can type into spin boxes.

I'm going to post this comment now, and then try logging in with a different Wayland DE to see how it behaves with a compositor that isn't KWin.

**Comment by kbloom** [comment]
Entering text in a spin-box works in Cosmic, regardless of whether MU_QT_QPA_PLATFORM is set.

**Comment by mrbumpy409** [comment]
I can confirm that setting `MU_QT_QPA_PLATFORM=1` works around the bug. However, it also makes it impossible to drag toolbars to a new location.

**Comment by moritzruth** [comment]
Keyboard input does not work at all in [Hyprland](https://github.com/hyprwm/Hyprland) when using the AppImage or Flatpak.

(As a workaround, I am running MuseScore in a Fedora container using [distrobox](https://github.com/89luca89/distrobox), but this breaks trackpad gestures: pinch-to-zoom does not work and two-finger-scrolling is extremely slow.)

**Comment by mrbumpy409** [comment]
I've just discovered a workaround for this problem under KDE Plasma:

1. Go into **System Settings** → **Application Permissions** (under **Security & Privacy**) → **Legacy X11 App Support**.
2. Under "Listening for keystrokes", select "Always allowed". (The default is "As above, plus any key pressed...").

You will be warned that "...using this setting will reduce system security and permit malicious software to steal passwords and spy on the text that you type. Make sure you understand and accept this risk."

After changing this setting, all keyboard input works as expected in MuseScore Studio.

I have also [filed a bug report](https://bugs.kde.org/show_bug.cgi?id=511679) against KDE's xwayland implementation.

**Comment by Zamundaaa** [comment]
So the ultimate cause of the problem is that MuseScore does something rather nonsensical with popups: They're override redirect windows and at the same time don't do a keyboard grab. The normal window loses focus, but override redirect windows don't get focus, so no window is focused and thus no input is forwarded to Xwayland.

As Unreal Engine 5 does something similarly bad, we looked into a workaround on the KWin side that seems feasible, but it would still be good to solve the underlying issue.

**Comment by cbjeukendrup** [comment]
Does https://github.com/musescore/MuseScore/pull/29888 (i.e. removing `Qt::BypassWindowManagerHint`) improve the situation regarding that? 

(If I understand things correctly, the reason that it isn't merged yet is that we were figuring out the exact condition for when to use `Qt::BypassWindowManagerHint`, because in some conditions its removal breaks accessibility things.)

**Comment by Zamundaaa** [comment]
It should fix it, yes. I'm surprised `BypassWindowManagerHint` affects accessibility though.

**Comment by Eism** [comment]
Hello! Could you please test this build? https://github.com/musescore/MuseScore/actions/runs/19538823217/artifacts/4628070726

**Comment by kbloom** [comment]
With [this build](https://github.com/musescore/MuseScore/actions/runs/19538823217/artifacts/4628070726), when running it using the default XWayland, none of the controls in the Time signature popup in the new score wizard respond to input -- neither clicks nor keyboard.

With MU_QT_QPA_PLATFORM=1, to force MuseScore to use Wayland, the controls still don't work. In addition, the build regresses on issue https://github.com/musescore/MuseScore/issues/15285, and menus now appear in the center of their parent window again, instead of attached where they're supposed to be.

**Comment by MarcSabatella** [comment]
FWIW, the issue of the popups not working is not related to this build; it's true of nightlies as well.  See https://github.com/musescore/MuseScore/issues/31114

**Comment by kbloom** [comment]
That issue sounds related to the one we're trying to fix here, at least in a way that makes it impossible to further test builds for this issue until that one is fixed. Or is there another affected control that I can be testing that's not affected by #31114?

**Comment by cbjeukendrup** [comment]
The popups in the Properties panel? (for any element, "Playback" and "Appearance")

**Comment by kbloom** [comment]
With that build, the popups in the Properties panel not respond to keyboard input under XWayland. 

Under Wayland, there's apparently a whole lot more that's broken.
* The zoom level is very wierd.
* I can't even click on the clef sign to select it (so that I can get to one of those popups).
* When I click to input notes, they end up in the wrong place.

After entering a note, I can change it's properties. So I pop up the appearance panel:
  * **Typing numbers into the combo box works.**
  * I can't close the appearance popup when I'm done. Clicking outside the appearance popup doesn't make it go away. Clicking the "Appearance" button in the properties panel to close the popup makes all of the controls in the popup go away, but the popup itself remains, empty.

**Comment by Eism** [comment]
@kbloom thank you for testing. There is [a new build](https://github.com/musescore/MuseScore/actions/runs/19625290158/artifacts/4657039257) 

could you please test it and send your diagnostics files? Main menu -> Diagnostics -> Save diagnostic files

**Comment by kbloom** [comment]
Build 253280622:

Under XWayland:

 * The Time Signature popup in the New Score wizard responds to the backspace key and up/down arrow keys, but not the number keys.
 * Likewise for the appearance popup in the "Properties" panel.

Under Wayland (MU_QT_QPA_PLATFORM=1)

* Menus pop up in the middle of the window. (Regression of https://github.com/musescore/MuseScore/issues/15285)
* Typing numbers into the time signature popup in the new score wizard works correctly.

I tested the release version 4.6.3 with MU_QT_QPA_PLATFORM=1, and the scaling and inability to select parts of the score are bugs in that version too. So that has nothing to do with the builds we're testing, and I'm going to see if there's another issue open for that, and if not, I'll file one with a screencast. (The menus in 4.6.3 open in the right place under Wayland, so I think that behavior is a regression caused by the fix we're trying to test here.)

**Comment by kbloom** [comment]
[Build_253280622_Wayland.zip](https://github.com/user-attachments/files/23725997/Build_253280622_Wayland.zip)
[Build_253280622_XWayland.zip](https://github.com/user-attachments/files/23725998/Build_253280622_XWayland.zip)

**Comment by kbloom** [comment]
So I think my issue is that you're trying to check for `QSysInfo::productType() == "ubuntu"`, but I've been testing on either Manjaro, or on Debian. I'm building a new version of your PR that I think is logically simpler about how it composes the window flags than the PR that you've been testing. If it works, I'll upload it.

**Comment by kbloom** [comment]
I did some more testing (of my PR) under some other compositors. My PR shouldn't affect other compositors, so the behavior of my build should be identical to the behavior of the 4.6.3.

* labwc:
  * Entering text in spin-boxes works under XWayland
  * Entering text in spin-boxes does not work under Wayland (MU_QT_QPA_PLATFORM=1)
  * Interaction with the score works just fine under Wayland. It's not scaled funny or offset in any way.
* cosmic-desktop alpha.
  * Entering text in spin-boxes works under both XWayland and Wayland. (So no fixes needed.)
  * Popups are mispositioned in XWayland, but not Wayland.
  * Interaction with the score works just fine under Wayland. It's not scaled funny or offset in any way.

**Comment by Eism** [comment]
Thanks for the detailed testing!
But I didn’t quite understand, if we remove `QSysInfo::productType() == "ubuntu"`, does that actually fix the issues on your side?
(please apply that change on top of my PR and let me know)

**Comment by kbloom** [comment]
I won't be able to try building your commit until later (I'm on a debian Machine with Qt 6.8), but in the meantime, you can try https://github.com/musescore/MuseScore/pull/31179, which I think makes it clearer what the fix is, and makes it clearer that it won't regress on popup positioning on any platform.

**Comment by Eism** [comment]
@kbloom 
I'm happy to merge your PR, but let's move the flag retrieval to a separate function, like mine: resolveWindowFlags.
Then you confirm that it works on your systems, @DmitryArefiev confirms that it works on his systems, and then we'll merge the solution. Ok?

**Comment by kbloom** [comment]
Sure. I can do that a bit later.

**Comment by kbloom** [comment]
Done, and pushed. I'll also have version for the master branch shortly.

**Comment by kbloom** [comment]
https://github.com/musescore/MuseScore/pull/31212 is my pull request for the master branch.

**Comment by DmitryArefiev** [comment]
Fixed in #31212 (#31179)
