### ISSUE TITLE
[Qt6.9] Some text has opposite color (black instead of white) in some plugins

### ISSUE THREAD

**Issue by DmitryArefiev** [musescore/MuseScore#28906]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

https://github.com/user-attachments/assets/4fb38b03-71c0-4970-9c5b-9e0561f7a381

### Supporting files, videos and screenshots

1

### What is the latest version of MuseScore Studio where this issue is present?

4.6.0-252020329

### Regression

Yes, this works in the latest released version and is broken in the nightly builds

### Operating system

Windows 10

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by cbjeukendrup** [comment]
The courtesy accidentals case should have been fixed by https://github.com/musescore/MuseScore/pull/28839

**Comment by cbjeukendrup** [comment]
Perhaps https://doc.qt.io/qt-6/qstylehints.html#colorScheme-prop can help to prevent this and similar problems

**Comment by igorkorsukov** [comment]
@DmitryArefiev please recheck, don't reproduced for me

**Comment by DmitryArefiev** [comment]
@igorkorsukov Rechecked in master and 4.6 nightly builds (4.7.0-252320321 and 4.6.0-252320405) on Win10. 
**Still occurs** on my side with:

* Tuning
* Modal Tuning 
* Modal Temperaments
* Lilypond Lyrics
* Mirror Intervals

https://github.com/user-attachments/assets/6d30373b-989b-4378-807d-b35737df0ed2

**Comment by igorkorsukov** [comment]
Was able to reproduce. The system theme needs to be light (before this I had a dark one)

**Comment by igorkorsukov** [comment]
> Perhaps https://doc.qt.io/qt-6/qstylehints.html#colorScheme-prop can help to prevent this and similar problems

Doesn't work (
So far I have not been able to solve this problem.
It appears when the application theme differs from the OS theme and only for plugins, because they use components from Qt, not ours.

I will return to this problem later.

**Comment by zacjansheski** [comment]
I'm seeing this on Linux on tuning plug-ins in light mode

<img width="851" height="775" alt="Image" src="https://github.com/user-attachments/assets/179ba953-f6a2-4409-90a9-836c0639a7e0" />

**Comment by bkunda** [comment]
We should probably check back in on this issue. 

The three old tuning-related plugins have since been superseded by one new tuning plugin, which seems to appear correctly to me. 

The only one that currently renders badly for me is mirror notes, and only when in light mode and only on Windows:


<img width="450" height="227" alt="Image" src="https://github.com/user-attachments/assets/31c17bc1-388b-4766-869b-41fd594ef0a9" />

<img width="450" height="235" alt="Image" src="https://github.com/user-attachments/assets/40539c4c-069a-477e-8b03-57f828492afc" />

Lilipond lyrics is also a bit funky, but not unreadable at least:

<img width="1194" height="647" alt="Image" src="https://github.com/user-attachments/assets/734316e2-a5a6-4ac2-9511-daf3cb23762b" />

**Comment by igorkorsukov** [comment]
These plugins use UI components from Qt. They depend on the theme's system settings (light or dark). If the system settings don't match the MuseScore settings (dark or light), then a problem arises.

I couldn't find a way to make the Qt components obey our theme settings; I tried various options.
I think the best option is to rewrite these forms using our UI components. I plan to do this soon.
