### ISSUE TITLE
4.6.4,4.6.5 main window initially invisible on Linux if use Compton desktop compositor (Linux Mint MATE)

### ISSUE THREAD

**Issue by cebderby** [musescore/MuseScore#31620]
### Issue type

UI bug (incorrect info or interface appearance)

### Description with steps to reproduce

1. use Linux Mint MATE with desktop settings: Window Manager as Marco+Compton (or Metacity+Compton) ie. window compositor that allows transparency using GPU not CPU effects.  (Possibly Ubuntu MATE or other would also have the same, not tested)
2. launch one of the released .appimage files (with execute permission set) for 4.6.4 or 4.6.5 (issue starts at 4.6.4, previous were ok) or the latest nightly (eg at 31Dec'25)
3. note that splash window and first-ever start or startup tips (if enabled) windows appear as usual, and that a new tab/button 'MuseScore Studio' appears in task bar, and if hover mouse over it, the window content (eg a list of scores) is visible in the thumbnail (if enabled).   Also note that if try to interact with another window, there is no mouse focus available (if on part of the screen where the MuseScore window is meant to be showing)
4. to make MuseScore Studio visible, cause its window to be closed and reopened: either click once on the taskbar item (to minimise) and again (to unminimise), or if have a workspace switcher set up, switch to a different workspace and back again.  (Noting also in this case that the large MuseScore window had also appeared as expected in the workspace switcher's illustration of the desktop contents).
5. Initially I wondered if this happened to be a timing issue with my CPU and graphics card, but I have now had opportunity to try it on another computer with the same OS setup (different CPU and using built-in Intel graphics) and it is consistent there too.

### Supporting files, videos and screenshots

Screenshots:
1 desktop settings
2 launch appimage get splash window ok
3 get first-ever or startup tips window ok
4 no main window but taskbar item open and workspace switcher shows large window
5 hover over taskbar shows live window content thumbnail - exists just invisible
6 after minimise-unminimise or workspace switch away+back - all is then normal

![Image](https://github.com/user-attachments/assets/3d0ed74b-7157-416b-871c-3f1358f48dfe)
![Image](https://github.com/user-attachments/assets/f3b545d5-02c7-4c37-b07a-c64599d55eb6)
![Image](https://github.com/user-attachments/assets/59449123-1cf0-40d5-9a25-823969fa4aac)
![Image](https://github.com/user-attachments/assets/e3e5650c-4658-4260-a2bf-acc56f552b88)
![Image](https://github.com/user-attachments/assets/c09662e0-c8b0-4e26-bbf5-b72022db9b9c)
![Image](https://github.com/user-attachments/assets/90239e05-5cb9-47fe-b619-acb1cd6caed4)

### In which versions of MuseScore Studio is this issue present?

4.6.4, 4.6.5, nightly 31Dec25

### Regression

Yes, this used to work in a previous version of MuseScore 4.x

### Operating system

Linux Mint MATE 22(.2), if Compton desktop compositor in use

### Additional context

I note that the changes listed against the 4.6.4 release included an item regarding setting the main window invisible on startup to fix a (MS Windows) issue of flickering windows on start.  If this issue was specific to MS Windows and never a problem on Linux, then probably the transparency on start could be done conditionally for MS Windows and not for Linux/other.

The desktop window manager and compostor "Marco+Compton" is the preferred setting to use the available hardware and get the best display (video playback etc) even if no particular desktop effects (shadows, transparency etc) are wanted.   Use of the other settings (no compositor, or CPU-based compositor) fix this MuseScore-Studio startup issue if wanted, but are not preferred long term.

### Checklist

- [x] This report follows the [guidelines](https://github.com/musescore/MuseScore/wiki/Reporting-bugs-and-issues) for reporting bugs and issues
- [x] I have verified that this issue has not been logged before, by searching the [issue tracker](https://github.com/musescore/MuseScore/issues) for similar issues
- [x] I have attached all requested files and information to this report
- [x] I have attempted to identify the root problem as concisely as possible, and have used minimal reproducible examples where possible

**Comment by krasko78** [comment]
@cebderby Hi! I will attempt to fix this for you later today but I am not sure it will work. Will you be able to test it? I can give you instructions if you don't know how to test a PR build.

**Comment by cebderby** [comment]
Great, yes I should be able to test something later.  I found where the nightly builds were via https://musescore.org/en/nightly-builds
when I created the issue, if it's elsewhere can you point me to an Appimage when ready?  I don't have a git environment set up. Thanks.

**Comment by krasko78** [comment]
@cebderby Here is the [pull request](https://github.com/musescore/MuseScore/pull/32664) to test. It forces the main window to repaint after the transparency is removed. You can find instructions [how to test a Pull Request build here](https://github.com/musescore/MuseScore/wiki/Downloading-and-running-test-builds#downloading-builds-from-pull-requests). Let me know how it goes!

**Comment by cebderby** [comment]
Ok, found that ok, got the MuseScore-Studio-5.0.0.260317191-x86_64.AppImage out of the zip and ran it.

Unfortunately, 'repaint' action isn't enough, this window manager+compositor must have stored the transparent property of the window from while it was being created, as changing the window's size (with care, I can maximise-unmaximise it, or drag it larger using the size & position displayed in the workspace switcher as a guide to where it is, which would also repaint I think) isn't enough to get it to show.  

It's minimise+unminimise, (or workspace switch away and back) which makes it visible, which would both cause the window's 'frame' to be dropped from the window manager's currently displayed windows, then re-added with the (now) non-transparent property.  Presumably prior to 4.6.4, there was no transparency during the creation.

**Comment by krasko78** [comment]
I see. I had some serious doubts that it was not going to work anyway. Thanks for trying it out! In that case I'll close the PR and let's wait for the other issue to be addressed. The team may decide to drop the transparency hack altogether or keep it for Windows only. The focus right now is on the upcoming 4.7 release so everything else is lower priority. Luckily you have a workaround with the minimize/unminimize actions.

**Comment by krasko78** [comment]
@cebderby This has been fixed in the nightly builds since a few days. If you don't want to use a nightly build, you will have to wait until 5.0 is released.

**Comment by cebderby** [comment]
Tested [MU4_260824132_Lin_aarch64_34688_App start. Show the window only when content is ready](https://github.com/musescore/MuseScore/actions/runs/32732443316/artifacts/9522308289)
and it does NOT resolve the issue.
The main window remains transparent, same as 4.6.4 onwards including all of 4.7.x so far
