### ISSUE TITLE
[MU4 Issue] Keyboard shortcuts not implemented

### ISSUE THREAD

**Issue by vshalkevich** [musescore/MuseScore#7687]
**Describe the bug**
Shortcuts not working:
1. Change line or slur length with arrow keys
2. Range selection with arrow keys + shift
3. N to toggle Note Input (can enter but not exit currently)
4. Home, End keys to jump to beginning or end of score
5. Copy (Cmd+C) and Paste (Cmd+V) shortcuts not working (works via right-click though)
6. No keyboard control for number spinboxes (IncrementalPropertyControl) (Checked on Linux Ubunty)
7. No keyboard control for sliders (Checked on Linux Ubunty)
8. No keyboard navigation in ValueList (Checked on Linux Ubunty)

**To Reproduce**
1. Try to use shortcuts

**Expected behavior**
Shortcuts work

**Desktop (please complete the following information):**
MacOS
Windows 10

**Comment by iwoithe** [comment]
Not sure if it's connected or not, but when I tried compiling MuseScore (from [this](https://github.com/musescore/MuseScore/commit/5c1a1bb5812ff0be1064834bd844a6f20aa8d2d1) commit), it failed (OS: Windows 10, Compiler: MSYS Makefiles). Output of the error is below.
```
In file included from C:/iwoithe/Software/Source_Code/MuseScore/builds/Win-Qt5.15.0-mingw73_64-Make-RelWithDebInfo/src/framework/shortcuts/CMakeFiles/shortcuts.dir/Unity/unity_0_cxx.cxx:7:
C:/iwoithe/Software/Source_Code/MuseScore/src/framework/shortcuts/internal/shortcutsinstancemodel.cpp: In member function 'void mu::shortcuts::ShortcutsInstanceModel::load()':
C:/iwoithe/Software/Source_Code/MuseScore/src/framework/shortcuts/internal/shortcutsinstancemodel.cpp:59:39: error: no matching function for call to 'QShortcut::QShortcut(QString, QWidget*&, mu::shortcuts::ShortcutsInstanceModel::load()::<lambda()>, Qt::ShortcutContext)'
   59 |             }, Qt::ApplicationShortcut);
      |                                       ^
In file included from C:/Qt/Qt5.15.0/5.15.0/mingw73_64/include/QtWidgets/QShortcut:1,
                 from C:/iwoithe/Software/Source_Code/MuseScore/src/framework/shortcuts/internal/shortcutsinstancemodel.cpp:22,
                 from C:/iwoithe/Software/Source_Code/MuseScore/builds/Win-Qt5.15.0-mingw73_64-Make-RelWithDebInfo/src/framework/shortcuts/CMakeFiles/shortcuts.dir/Unity/unity_0_cxx.cxx:7:
C:/Qt/Qt5.15.0/5.15.0/mingw73_64/include/QtWidgets/qshortcut.h:64:5: note: candidate: 'QShortcut::QShortcut(const QKeySequence&, QWidget*, const char*, const char*, Qt::ShortcutContext)'
   64 |     QShortcut(const QKeySequence& key, QWidget *parent,
      |     ^~~~~~~~~
C:/Qt/Qt5.15.0/5.15.0/mingw73_64/include/QtWidgets/qshortcut.h:65:27: note:   no known conversion for argument 3 from 'mu::shortcuts::ShortcutsInstanceModel::load()::<lambda()>' to 'const char*'
   65 |               const char *member = nullptr, const char *ambiguousMember = nullptr,
      |               ~~~~~~~~~~~~^~~~~~~~~~~~~~~~
C:/Qt/Qt5.15.0/5.15.0/mingw73_64/include/QtWidgets/qshortcut.h:63:14: note: candidate: 'QShortcut::QShortcut(QWidget*)'
   63 |     explicit QShortcut(QWidget *parent);
      |              ^~~~~~~~~
C:/Qt/Qt5.15.0/5.15.0/mingw73_64/include/QtWidgets/qshortcut.h:63:14: note:   candidate expects 1 argument, 4 provided
make[2]: *** [src/framework/shortcuts/CMakeFiles/shortcuts.dir/build.make:112: src/framework/shortcuts/CMakeFiles/shortcuts.dir/Unity/unity_0_cxx.cxx.obj] Error 1
make[1]: *** [CMakeFiles/Makefile2:2010: src/framework/shortcuts/CMakeFiles/shortcuts.dir/all] Error 2
make: *** [Makefile:171: all] Error 2
```
I say this because after I fixed it, a majority of the mentioned shortcuts worked fine for me.

**Comment by wizofaus** [comment]
It seems many of these actions *aren't* handled via the shortcut mechanism at all in MU3, whereas in MU4 the shortcuts for, e.g. the arrow keys, are preventing the actions being handled.
This is actually partially fixed in https://github.com/musescore/MuseScore/pull/8337, but only when editing text elements, it needs to be expanded to work for other elements too.
